### ISSUE TITLE
Cannot edit

### ISSUE THREAD

**Issue by Boco10** [philippfrenzel/yii2fullcalendar#10]
Hello.

I cannot edit the events which was created during runtime. 

I've modified the yii2fullcalendar.php :
 public $clientOptions = [
        'weekends' => true,
        'default' => 'month',
        'editable' => true,
    ];

When i create the events:

```
        $Event = new \yii2fullcalendar\models\Event();
        $Event->id = $record->id;
        $Event->title = User::find()->where('id='.$record->user)->one()->username;
        $Event->editable = true;
        $Event->start = date($record->date);
        $Event->className = 'Ilness';
        $events[] = $Event;
```

The view:
<?= \yii2fullcalendar\yii2fullcalendar::widget(array(
                    'events'=>$model->getVacationDays(),
                    'options' => [
                        'id' => 'calendar',
                    ],
                    'clientOptions' => [
                        'selectable' => true,
                        'selectHelper' => true,
                        'droppable' => true,
                        'editable' => true,
                        'drop' => new JsExpression("function(date) {
                            alert('Dropped on ' + date.format());
                            if ($('#drop-remove').is(':checked')) {
                                // if so, remove the element from the 'Draggable Events' list
                                $(this).remove();
                            }
                        }"),
                        'select' => new JsExpression("function(start, end) {
                            $('#newEventModal').find('#startDate').val(start.format('YYYY-MM-DD'));
                            $('#newEventModal').find('#endDate').val(end.format('YYYY-MM-DD'));
                            $('#newEventModal').find('#user').val('".Yii::$app->user->username ."');

```
                        $('#newEventModal').modal('show');

                    }"),
                    'eventClick' => new JsExpression("function(calEvent, jsEvent, view) {
                            //alert('Event: ' + calEvent.title);
                            //alert('Coordinates: ' + jsEvent.pageX + ',' + jsEvent.pageY);
                            //alert('View: ' + view.name);

                            // change the border color just for fun
                            $(this).css('border-color', 'red');

                        }"),
                    'defaultDate' => date('Y-m-d')
              ],
          ));?>
```

But still i cant drag and drop that event

**Comment by Boco10** [comment]
Thanks for the nothing. The problem is your example is bad. Since you render every option for the event and if you create the event like your example then it will looks like this:

$('#calendar').fullCalendar('renderEvent',{"id":1,"title":"Boco10","allDay":true,"start":"2015-03-10","end":"2015-03-10","url":null,"className":"xxxxx","editable":true,"startEditable":null,"durationEditable":null,"source":null,"color":null,"backgroundColor":null,"borderColor":null,"textColor":null},1);

This way the events you just create cannot be edited even, if you specify the client option editable. You have to create the event in that way:

    		$Event = new \yii2fullcalendar\models\Event();
	    	$Event->id = $record->id;
	    	$Event->title = User::find()->where('id='.$record->user)->one()->username;
	    	$Event->editable = true;
                $Event->allDay = true;
	    	$Event->start = date($record->date);
                $Event->end = date($record->date);
                $Event->startEditable = true;
                $Event->durationEditable = true;

Which is a bug, since by default the fullCalendar (http://fullcalendar.io/docs/event_ui/eventDurationEditable/) documentation reflects that those settings (startEditable , durationEditable ) are true by default, but you set them to null.

Have a good day.

**Comment by philippfrenzel** [comment]
Hi @Boco10 , sorry for coming back late and thanks for posting the solution! I will update the docs this weekend, so the next user will not fall into the same issue! Cheers Philipp

**Comment by jonrmitchell** [comment]
As @Boco10  alluded to, when the yii2fullcalendar\models\Event objects are used, the corresponding FullCalendar events are uneditable because:
1) you declare `$editable`, `$startEditable`, and `$durationEditable` as variables in the Event class, and 
2) when the Event objects are serialized to JSON, if those variables have not been defined, they are still present in the JSON, but with values of null
3) when FullCalendar.js checks if an event should be editable, it checks if those fields are _defined_ - and being present and set to null counts as being defined, but falsy, so the event is determined not editable.

One fix then is to exclude undefined values from the seriealized JSON. This can be done by having your Event class  implements \JsonSerializable and then add the jsonSerialize function like so:

```
class Event extends Model implements \JsonSerializable {
    public function jsonSerialize() {
        return array_filter($this->attributes, function($var){return !is_null($var);} );
    }
}
```

This preserves the expected behavior of the FullCalendar Events.

**Comment by tbthiago** [comment]
Hi @Boco10 , the select event is working for you?
I copied exactly the same code from you, but nothing happens when I click in the calendar.

**Comment by philippfrenzel** [comment]
Hi, should I add the Serialize directly to the Events ? @jonrmitchell

**Comment by jonrmitchell** [comment]
Yep, you could add the `implements \JsonSerializable` declaration right to your `\yii2fullcalendar\models\Event` class, and then add that `jsonSerialize` method to the class, and then when Yii goes to serialize the objects to json it'll use that method over the default object-to-json method.

In my site, I was encountering the same issue as @Boco10, so I subclassed your Event class and added this feature and it fixed the "editable" problem.

**Comment by philippfrenzel** [comment]
Ok, then this will be added ! Thanks!
