### ISSUE TITLE
All day events not rendering

### ISSUE THREAD

**Issue by spiro-stathakis** [philippfrenzel/yii2fullcalendar#101]
Hi there, 
Thank you for fixing #99. I think there may be a new issue where allDay events are not being rendered within the all-day section.All my 'Event' objects have start and end times and some have allDay:true. Those are the ones that are missing. 

Thank you.

**Comment by philippfrenzel** [comment]
Hi, I had the same issue... :/ I need to fix it by doing it like this:

```php
   $Event->id = $periode->format('n') * -1;
   $Event->start = $periode->format('Y-m-d\TH:i:s\Z');
                        $endObj = clone $periode;
                        $endObj->modify('+1 day');
                        $Event->end = $endObj->format('Y-m-d\TH:i:s\Z');
                        $Event->allDay = true;
                        $Event->color = 'black';
                        $Event->durationEditable = false;
                        $events[] = $Event;
```

**Comment by spiro-stathakis** [comment]
Thank You  Phillip,

This is working for me too.
Is there going to be a fix to honour the allDay setting? I have to add fake
times to get the allDay rendering to work.

Regards,

Spiro

**Comment by philippfrenzel** [comment]
Hi, well I hope this will be fixed within one of the next upcoming releases from fullcalendar... You are welcome
