### ISSUE TITLE
 Class 'yii2fullcalendar\yii2fullcalendar' not found

### ISSUE THREAD

**Issue by yingzzai** [philippfrenzel/yii2fullcalendar#102]
<?= \yii2fullcalendar\yii2fullcalendar::widget(array(
            'events' => $events,
            'id' => 'calendar',
        ));
   ?>

Beginner yii2.0, how can I solve this problem?  thank you!

**Comment by philippfrenzel** [comment]
Hi, did you add the extension to your composer.json file and did you run 'composer update' afterwards?

**Comment by philippfrenzel** [comment]
and did you check to add

use yii2fullcalendar;

at the top of your script

**Comment by yingzzai** [comment]
Yes, it has been checked.  

I'm a composer file downloaded from \vendor\philippfrenzel\yii2fullcalendar.

**Comment by philippfrenzel** [comment]
you should run composer update instead of downloading a folder - the package will be added to the composer autoload files - which is needed because you need autoload classes ;)

**Comment by yingzzai** [comment]
I see. Thank you.

**Comment by philippfrenzel** [comment]
Ok, so I'll close this issue if you think it's still not working, pls. reopen it. Thanks

**Comment by yingzzai** [comment]
The file or directory to be published does not exist: F:\sun\WWW\tcoa1\vendor\bower/fullcalendar/dist  ?

I looked at other people's questions, but it's still a little bit unclear. Can you say why? How to do it? Thank you
