### ISSUE TITLE
This load has been loaded two times, do not know what reason? I need your help

### ISSUE THREAD

**Issue by 18829017810** [philippfrenzel/yii2fullcalendar#104]
The place of printing appeared two times???   

 protected function getClientOptions()
    {
        $id = $this->options['id'];
        $options['loading'] = new JsExpression("function(isLoading, view ) {
            console.log(\"555555555555555\");
            jQuery('#{$id}').find('.fc-loading').toggle(isLoading);
            var csrfToken = $('meta[name=\"csrf-token\"]').attr(\"content\");
            var tag = 1;
            console.log(\"6666666666666\");
            $.ajax({
	            url : 'http://localhost/tcoa1/tcoa1/web/calendar/getrequest',
	            dataType: 'json',
	            type  : 'GET',
	            async: false,
	            data: {
	                tag:tag,
	                _csrf:csrfToken,
	            },
	            success: function (data, response) {}
});

**Comment by philippfrenzel** [comment]
Hi,
what do you mean with the place of printing appeared two times?

**Comment by 18829017810** [comment]
I've solved this problem, and a breakpoint to the JS is found, regardless of whether the isloading is true or false, the program will enter, and this function executes two times. Finally, I added a judgment, thank you very much for your reply!

**Comment by philippfrenzel** [comment]
Thanks @18829017810 so I'll close this issue for now
