### ISSUE TITLE
Yii::$app->language Error

### ISSUE THREAD

**Issue by lucianoffranca** [philippfrenzel/yii2fullcalendar#109]
I'm using the philippfrenzel/yii2fullcalendar package this plugin
automatically configures Yii::$app->language e and performs the mapping
to translate the interface. However, the code does not take into account
characters when the language configuration files
of this plugin are all in lowercase letters.

```
System setup:
config / main.php
    return [
    .....
    'language'=>'pt-BR'
    ....
```

Code used:
view/xyz/index.php
```
  <?= \yii2fullcalendar\yii2fullcalendar::widget([
        'options' => [
            'lang' => strtolower(Yii::$app->language), //'pt-BR'=>'pt-br'
        ],
```

I think the plugin could insert a code to solve this problem
vendor/philippfrenze/yii2fullcalendar/CoreAsset.php

Original:
```
    public function registerAssetFiles($view)
    {
        $language = $this->language ? $this->language : Yii::$app->language;
        if (strtoupper($language) != 'EN-US') 
        {
            $this->js[] = "locale/{$language}.js";
        }
```

Changes:
```
    public function registerAssetFiles($view)
    {
        $language = $this->language ? $this->language : Yii::$app->language;
        if (strtoupper($language) != 'EN-US') 
        {
            $this->js[] = "locale/".strtolower($language).".js";
        }
```

**Comment by philippfrenzel** [comment]
hey, I guess you forgott top add the 
use Yii;

Statement in your class or you can make an absolute class call like
\Yii::$app->language

?
