### ISSUE TITLE
add scheduler plugin

### ISSUE THREAD

**Issue by akorinek** [philippfrenzel/yii2fullcalendar#112]
Would be nice to have the scheduler plugin added, that way I can simply add my license number and have it available. There is also a free trial license available, as well as for open source projects.

**Comment by philippfrenzel** [comment]
Hi - sorry I¨m bussy at the moment, I will take a look the next couple of weeks - you are always welcome to create a pull request ;)

**Comment by akorinek** [comment]
Hi, no problem, I think there is not much to change in the code. I'll add a PR, this isn't fully tested, I failed at updating the modified package using composer, not sure why it would not pick up the new dependency.

**Comment by philippfrenzel** [comment]
hey, i merged your pull requests and hope it will work out fine... and because of your package inclusion - which version of FXP composer plugin are you using

**Comment by akorinek** [comment]
Hi,

thanks for the merge. I'm using 1.4.2 or the FXP composer plugin. I'm getting a strange problem with the fullcalendar package:

Your requirements could not be resolved to an installable set of packages.                                     

  Problem 1
    - Installation request for philippfrenzel/yii2fullcalendar dev-master -> satisfiable by philippfrenzel/yii2fullcalendar[dev-master].
    - philippfrenzel/yii2fullcalendar dev-master requires bower-asset/fullcalendar 3.8.0@stable -> no matching package found.

Any idea what that could be?

**Comment by philippfrenzel** [comment]
hmm, you still have this issue?

**Comment by akorinek** [comment]
Thanks for the update, everything works now. I've switched away from the FXP composer plugin to asset composer since it's much faster anyway and gives less of these problems.

**Comment by philippfrenzel** [comment]
Hi, thanks for the feedback, I'll check the asset composer to see if it works for me too ;)
