### ISSUE TITLE
how to display google calendar events along with events from the database?

### ISSUE THREAD

**Issue by cla-dev** [philippfrenzel/yii2fullcalendar#124]
Hi,

I am new to this plugin and need to display both google events and events from the database on the same calendar. I have it working with either google events or events from the database, but not both.

when I set the clientOptions to display the google events, then all the database events do not display.

please help!

thanks,

Rovin

**Comment by philippfrenzel** [comment]
Hi, guess you need to merge them on the server side?

**Comment by cla-dev** [comment]
Hi again,

in the fullcalendar.io docs it mentions using eventSources to set multiple event sources, however I do not see that implemented in yii2fullcalendar?

please advise...

thanks,

Rovin

**Comment by cla-dev** [comment]
Hi Philip,
I figured it out :)

here is the code for those looking to do the same:

<?= \yii2fullcalendar\yii2fullcalendar::widget(['header'=>['left'=>"today prev,next",'center'=> "title",'right'=>"basicWeek,month"],
                                                        'id'=>'dash-calendar',
                                                        'googleCalendar'=>true,
                                                        'clientOptions'=>[
                                                        'googleCalendarApiKey'=>'<YOUR API KEY>',
                                                            'eventSources'=>[
	                                                            $dbevents, //events array from database
                                                                ['googleCalendarId'=>'en.sr#holiday@group.v.calendar.google.com', //events from the google calendar
                                                                    'allDayDefault'=>true,
                                                                    'color'=>'orange',
                                                                ],
                                                            ]
                                                        ],
                                                        'defaultView'=>'month',
                                                        ])?>

**Comment by cla-dev** [comment]
`<?= \yii2fullcalendar\yii2fullcalendar::widget(['header'=>['left'=>"today prev,next",'center'=> "title",'right'=>"basicWeek,month"],
                                                        'id'=>'dash-calendar',
                                                        'googleCalendar'=>true,
                                                        'clientOptions'=>[
                                                        'googleCalendarApiKey'=>'<YOUR API KEY>',
                                                            'eventSources'=>[
	                                                            $dbevents, //events array from database
                                                                ['googleCalendarId'=>'en.sr#holiday@group.v.calendar.google.com', //events from public google calendar
                                                                    'allDayDefault'=>true,
                                                                    'color'=>'orange',
                                                                ],
                                                            ]
                                                        ],
                                                        'defaultView'=>'month',
                                                        ])?>`

**Comment by cla-dev** [comment]
happy coding folks!
