### ISSUE TITLE
Creating default object from empty value

### ISSUE THREAD

**Issue by adyoi** [philippfrenzel/yii2fullcalendar#135]
$event->nonstandard

**Comment by philippfrenzel** [comment]
did you try to first initiate the $event as an Object ?

**Comment by philippfrenzel** [comment]
Hi @adyoi did you solve this issue - i will close it, if you still have this issue, pls. let me know

**Comment by adyoi** [comment]
> did you try to first initiate the $event as an Object ?

$Event = new \yii2fullcalendar\models\Event();
