### ISSUE TITLE
Google Calendar

### ISSUE THREAD

**Issue by gunzino** [philippfrenzel/yii2fullcalendar#14]
Hello,

I would like to ask if it's possible to use google calendar with this extension,
My code is:

<?= \yii2fullcalendar\yii2fullcalendar::widget(array(
    'id' => 'calendar',
    'events' => $events,
    'googleCalendar' => true,
    'googleCalendarApiKey' => 'xxxxxxx',
    'clientOptions' => [
        'editable' => false,
        'weekends' => true,
        // 'eventLimitClick' => 'popover',
        'theme' => true,
        'dayClick' => new JsExpression($JSEventDayClick),
        'eventClick' => new JsExpression($JSEventClick)
    ],

));
?>

But this does not work. But I see the googleCalendar in the class reference.

**Comment by philippfrenzel** [comment]
Hmm, ill take a Look AT this in about 6 hours... Pls take a look at full calendar.io and the sample by the lib author

**Comment by gunzino** [comment]
Okay thank you, I have already checked the documentation on calendar.io, I have tried to put it in JS code like this:
$JSGoogleCalendar = <<<JS

$(document).ready(function() {
    $('#calendar').fullCalendar({
        googleCalendarApiKey: 'xxxxxxxxx',
        events: [
            {
                googleCalendarId: 'gunzo@gunzo.eu'
            }
        ]
    });
});

JS;

$this->registerJs($JSGoogleCalendar, \yii\web\View::POS_READY);



But this did not work too.

**Comment by philippfrenzel** [comment]
Hmm, I saw that googleCalender is enabled by setting "true" and although the rest of youer script seems to work fine... I'll check the code and build an sample on my "demo-page".... talk to you later

**Comment by gunzino** [comment]
Thank you. I saw the "true" setting too, but it did not load any events from the Google. I followed the docs here http://fullcalendar.io/docs/google_calendar/

**Comment by philippfrenzel** [comment]
Hi, did you get it to run?
