### ISSUE TITLE
EventClick Yii2 modal plugin documentation

### ISSUE THREAD

**Issue by xiandalisay** [philippfrenzel/yii2fullcalendar#17]
Is there any documentation to implement clicking and hovering of events like...

<?= yii2fullcalendar\yii2fullcalendar::widget([
       'events' => $activities,
       'eventClick' => 'function(calEvent, jsEvent, view) {
               //insert yii2 modal plugin for displaying the information regarding the events
              
      }'
    ]);
?>

**Comment by philippfrenzel** [comment]
you'll find information about it at the original plugin site, as so many people ask for it, I will add a tiny "docs" section over the weekend - until then I will not make it as to much stuff at work... You are always welcome to create a pull request ;) So take a look at sunday - cheers Phil

**Comment by philippfrenzel** [comment]
https://github.com/philippfrenzel/yii2fullcalendar-demo/blob/master/views/site/index.php 

if you wanna have a "tiny" sample

**Comment by xiandalisay** [comment]
Thanks. I'm trying to implement one. For example, krajee's PopoverX which is based on Modal bootstrap. http://demos.krajee.com/popover-x

**Comment by philippfrenzel** [comment]
ok, thats a good idea - just be aware to renderAjax while you open the modal - and can be that you have to "preload" the assets in the "main-Layout" ;)

**Comment by zmoddynamics** [comment]
Thank you so much for that sample on how to add methods during the widget setup. Was wrapping my brain around that all day!

**Comment by philippfrenzel** [comment]
I close this, if you still need input, pls. reopen and let me know!
