### ISSUE TITLE
jquery-ui is included regardless of whether theming is enabled...

### ISSUE THREAD

**Issue by qdii** [philippfrenzel/yii2fullcalendar#18]
... and it defaces my page.
Here is a minimum view I use to show the problem:
```php
<?php
use yii\helpers\Html;

echo Html::beginTag('div', ['class' => 'page-header']);
echo Html::beginTag('h1');
echo \yii\bootstrap\ButtonDropdown::widget([
    'label' =>'<span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>',
    'encodeLabel' => false,
    'options' => [ 'class' => 'btn-default' ],
    'dropdown' => [
        'items' => [
            ['label' => 'DropdownA', 'url' => '/'],
            ['label' => 'DropdownB', 'url' => '#'],
        ]
    ]
]);
echo ' Test';
echo Html::endTag('h1');
echo Html::endTag('div');

echo \yii2fullcalendar\yii2fullcalendar::widget([]);
```

The button dropdown looks gigantic on the view, because jquery-ui adds its own classes to it (`ui-widget` and whatnot). If I comment out the dependency in `CoreAsset.php`, then everything works.

I suggest registering jquery ui only when fullcalendar theming option is enabled.

**Comment by philippfrenzel** [comment]
hmm, can you pls. help me a bit on what exactly you wanna achieve? I can add an option to disable loading the jquery-ui assets?!

**Comment by philippfrenzel** [comment]
sorry - already late .. i follow your suggestion and fix the code tomorrow... looks like I'm to tired right now *gg*

**Comment by qdii** [comment]
Ideally, I would like `JuiAsset::register($view)` to be called only if `$this->clientOptions['theme']` is true. An option to disable loading it would work too :)

**Comment by philippfrenzel** [comment]
will do it like this;)

**Comment by philippfrenzel** [comment]
is it ok for you, if i pack it into the options? Makes more sense to me!

**Comment by qdii** [comment]
Looks perfect to me!

**Comment by philippfrenzel** [comment]
you are always welcome! ;)
