### ISSUE TITLE
en-us.js not found

### ISSUE THREAD

**Issue by zmoddynamics** [philippfrenzel/yii2fullcalendar#20]
Hi, this appears to be the same issue as mentioned below. 

https://github.com/thiagotalma/yii2-talma-fullcalendar-widget/issues/6

**Comment by philippfrenzel** [comment]
yes, that's correct;) Same js lib, same issues... The problem is, that for the "normal" I18N you need the syntax en-us... so what I might be able to offer is to implement a matching table, that will add the correct prefix to the language...?

**Comment by philippfrenzel** [comment]
Hi @zmoddynamics did you find a workaround? Thanks for a update?!

**Comment by bhavuksuthar** [comment]
use the same solution they have used and it will do the trick

**Comment by jslight** [comment]
`Yii::$app->language` returns the country part as uppercase yet this part is all lowercase:
`if ($language != 'en-us')`

`$language = $this->language ? $this->language : Yii::$app->language;`
should be changed to
`$language = strtolower($this->language ? $this->language : Yii::$app->language);`

**Comment by philippfrenzel** [comment]
Thanks! Will fix it in about an hour!

**Comment by ukashka** [comment]
Thanks jslight, yes I had the same problem, and your code helped me :) I changed the function code like this as u said:   public function registerAssetFiles($view)
    {
        // $language = $this->language ? $this->language : Yii::$app->language;
        $language = strtolower($this->language ? $this->language : Yii::$app->language);
        if ($language != 'en-us') 
        {
            $this->js[] = "lang/{$language}.js";
        }

        if($this->googleCalendar)
        {
            $this->js[] = 'gcal.js';
        }

        parent::registerAssetFiles($view);
    }

Also many thanks to philippfrenzel to create this extension

**Comment by philippfrenzel** [comment]
Thanks for sharing knowledge! And you are alwayse welcome - sorry for taking so long to answer! I'm happy you help each other! ;)
