### ISSUE TITLE
dependence from YiiAsset

### ISSUE THREAD

**Issue by evgkan** [philippfrenzel/yii2fullcalendar#21]
Hi.
fullcalendar.js is may connected before jquery.js by default.
Can you add dependences to CoreAsset.php like:
public $depends = [
        'yii\web\YiiAsset',
        'yii2fullcalendar\MomentAsset',
        'yii2fullcalendar\PrintAsset'
    ];
?

**Comment by philippfrenzel** [comment]
of course i can;) you are always welcome to create a pull request for this;)
