### ISSUE TITLE
Week eventes

### ISSUE THREAD

**Issue by dasturchiuz** [philippfrenzel/yii2fullcalendar#23]
How to all Sunday add event?

**Comment by philippfrenzel** [comment]
take a look at the fullcalender documentation -> PARAM allDayEvent ;)

**Comment by dasturchiuz** [comment]
Yii2 example is that possible?

**Comment by philippfrenzel** [comment]
I’ll try to make it next weekend - actually very busy

**Comment by dasturchiuz** [comment]
Thank you in advance, men inglizcha zo'r emas menda, Kechirasiz

**Comment by philippfrenzel** [comment]
`
$events = null;

        $startDateObj = new DateTime($startDate);
        $startDateObj->modify('+1 month');
        $endDateObj = new DateTime($endDate);
        $endDateObj->modify('-1 month');

        $activities = self::find()
            ->where('next_at >= ' . (int)$endDateObj->getTimestamp() . ' AND next_at <= ' . (int)$startDateObj->getTimestamp())
            ->all();

        foreach($activities AS $acti)
        {
            $Event = new \yii2fullcalendar\models\Event();            

            //try to get entity by class
            $EntityModel = \Yii::createObject($acti->entity);
            $Entity = $EntityModel::find()->where([$EntityModel::tableName() . '.id' => $acti->entity_id])->One();
            if(is_null($Entity) OR is_null($entityTitleField) OR $entityTitleField === '')
            {
                $Event->title = $acti->NextTypeAsString;
            }
            else
            {
                $Event->title = $acti->NextTypeAsString . ' ' . $Entity->{$entityTitleField};
            }

            $Event->id = $acti->entity_id;
            $timeStamp = $acti->next_at;            
            //$startObj = new DateTime();
            $startObj = new DateTime(\Yii::$app->formatter->asDateTime($timeStamp));
            $Event->start = $startObj->format('Y-m-d\Th:i:s\Z');
            $endObj = clone $startObj;
            $endObj->modify('+30 minutes');
            $Event->end = $endObj->format('Y-m-d\Th:i:s\Z');
            $Event->allDay = false;
            $events[] = $Event;
        }

        return $events;
`
