### ISSUE TITLE
i cant change color of event,

### ISSUE THREAD

**Issue by ajkosh** [philippfrenzel/yii2fullcalendar#24]
```
  <?= \yii2fullcalendar\yii2fullcalendar::widget(array(
      'events'=> $event,
      'clientOptions'=>[
      'weekends'=>true,
      'hiddenDays'=>[0],
      ],
    ));?>
```

**Comment by philippfrenzel** [comment]
pls. see fullcalendar.io documentation and check for view properties, this should let you change the color within clientOptions - pls. let me know if that works for you? Thanks Philipp

**Comment by nagaokashi** [comment]
I can't change the background color and textcolor.
View:
<?= \yii2fullcalendar\yii2fullcalendar::widget(array(
        'options' => [
        ],
        'clientOptions' => [
            'allDaySlot' => false,
            'selectHelper' => true,
            'eventClick' => new JsExpression($JSEventClick),
            'dayClick' => new JsExpression($JSDayClick),
            'defaultView' => 'agendaWeek',
            'header' => [
                'center'=>'prev,next today',
                'left'=>'',
                'right'=>'agendaDay,agendaWeek,month',
            ],
        ],
       'ajaxEvents' => Url::to(['/datsan/jsoncalendar', 'id_sanCon' => $modelSanCon->id])
    ));

Controller:
if (!empty($events)) {
                    foreach ($events as $eve) {
                        $event = new \yii2fullcalendar\models\Event();
                        $event->id = $eve->id;
                        $event->title = $eve->tieuDe;
                        $event->start = $eve->ngayBatDau . ' ' . $eve->gioBatDau;
                        $event->end = $eve->ngayKetThuc . ' ' . $eve->gioKetThuc;
                        $event->backgroundColor = $this->isDatsanAuthor($eve->id_nguoiDat) ? "yellow" : "blue";
                        $event->textColor = $this->isDatsanAuthor($eve->id_nguoiDat) ? "black" : "white";
                        $tasks[] = $event;
                    }
                }
