### ISSUE TITLE
syntax error, unexpected 'public' (T_PUBLIC), expecting ',' or ';'

### ISSUE THREAD

**Issue by ajkosh** [philippfrenzel/yii2fullcalendar#33]
description has no semi colon. 

![screenshot from 2015-12-22 11 31 02](https://cloud.githubusercontent.com/assets/8582472/11948928/8ca22284-a89f-11e5-99b1-de2a7d7f076c.png)

**Comment by philippfrenzel** [comment]
fixed with latest commit! Thanks for reporting!
