### ISSUE TITLE
getting 404 for en-us.js in lang directory

### ISSUE THREAD

**Issue by gigilsu** [philippfrenzel/yii2fullcalendar#37]
I'm not sure if this issue is that the file is actually missing from fullcalendar or if it is looking for it unnecessarily since en-us.js is the default language. Could you look into this?

**Comment by philippfrenzel** [comment]
Hi, how did you define your lang param in config?

**Comment by gigilsu** [comment]
I didn't, as en-us is the default

**Comment by philippfrenzel** [comment]
I found the issue, the exception in code is case sensitive, will fix it!

**Comment by philippfrenzel** [comment]
fixed with latest commit - thanks for reporting
