### ISSUE TITLE
editable not working

### ISSUE THREAD

**Issue by tbthiago** [philippfrenzel/yii2fullcalendar#38]
I put the editable option equals to true on clientOptions, but it's not working. The events are simply not editable.

<?= yii2fullcalendar\yii2fullcalendar::widget([
      		'clientOptions' => [
		        'defaultView'=> 'agendaWeek',
		    	'lang'=>'pt-br',
		      	'minTime'=> '06:00:00', //colocar como opcao
		      	'maxTime'=> '23:00:00', //colocar como opcao
		      	'allDaySlot'=> false,
      			'editable' => true,
      			'droppable' => true,
      		],
 			'header'=> [
 				'left'=> 'prev,next today',
 				'center'=> 'title',
 				'right' => 'agendaWeek,agendaDay'
 			],
 			'events'=>$events
	    ]);
	?>

**Comment by philippfrenzel** [comment]
hmm, I'll take a look at this later that day... - thanks for adding the issue!

**Comment by tbthiago** [comment]
I think it's not an issue with your plugin.
It's something related to yii2 jquery loading, or the order.
I didn't figure out yet.
Sorry, anyway.

**Comment by tbthiago** [comment]
Ok,
The weird is that only this options is not working, all other were recognized.

**Comment by tbthiago** [comment]
I got it. You Event class has attributes $editable, $startEditable and $durationEditable that were overwriting with false. Or you should set all as true on event, or set default as true on class.

**Comment by philippfrenzel** [comment]
You miss:

selectable => true,
selectableHelper => true
