### ISSUE TITLE
Event not rendering from Ajax

### ISSUE THREAD

**Issue by djkumar** [philippfrenzel/yii2fullcalendar#39]
Hey Philip, I've been using this extension for my project, I can create the event on the weekview design, But i can't able to retrieve the stored events from the database.
Here is the sample ajax returned value. 
Can give a suggestion on this

![11](https://cloud.githubusercontent.com/assets/16938026/13918766/4b555594-ef8f-11e5-9271-b6ab698edee8.png)

**Comment by philippfrenzel** [comment]
hmm, the initial data doesn't seem that wrong - it looks like you have all mandantory fields available... Here is a sample code that works for me:
`
/**
     * Renders the activities inside a calendar... might be nicer to view
     * @param  [type] $start [description]
     * @param  [type] $end   [description]
     * @param  [type] $_     [description]
     * @return [type]        [description]
     */
    public function actionJsoncalendar($start=NULL,$end=NULL,$entity=NULL,$entity_id=NULL,$_=NULL, $entityTitleField = NULL){
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        if($start = null)
        {
            $startObj = new DateTime();
            $start = $startObj->format('U');
        }

        $events = Activity::getCalendarActivities($start,$end,$entity,$entity_id, $entityTitleField);
        return $events;
    }
`

and within calendar
`
yii2fullcalendar\yii2fullcalendar::widget([
          'options' => [
            'lang' => substr(\Yii::$app->language,0,2),
            'class' => 'fullcalendar'
          ],
          'header' => [
            'left' => 'prev',
            'center' => 'title',
            'right' => 'next'
          ],  
          'clientOptions' => [
                'defaultView' => 'month',
                'height' => 450,
                'selectable' => true,
                'selectHelper' => true,
                'defaultDate' => date('Y-m-d'),
                'eventClick' => new JsExpression($JSEventClick),
                'eventLimit' => true
          ],
          'ajaxEvents' => Url::toRoute(['/activity/default/jsoncalendar','entity' => $entity, 'entityTitleField' => $entityTitleField])
        ]);
`

**Comment by djkumar** [comment]
Hey Thanks much.
It got working.
