### ISSUE TITLE
Directory vendor/bower/fullcalendar is empty

### ISSUE THREAD

**Issue by fruppel** [philippfrenzel/yii2fullcalendar#4]
Hi,

I just updated my application via composer and I have also seen that you changed the way fullcalendar and moment.js are included. The directories vendor/bower/fullcalendar and vendor/bower/moment were successfully created. The moment directory looks good but the fullcalendar directory is empty. Any idea why?

This is the content of my composer.json:
```
{
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Application Template",
    "keywords": ["yii2", "framework", "basic", "application template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
		"kartik-v/yii2-widgets": "*",
		"kartik-v/yii2-grid": "*",
        "kartik-v/yii2-detail-view": "*",
        "kartik-v/yii2-mpdf": "@dev",
        "kartik-v/yii2-money": "*",
        "webvimark/module-user-management": "*",
        "webvimark/bootstrap-switch": "*",
        "2amigos/yii2-tinymce-widget" : "*",
        "creocoder/yii2-nested-sets": "dev-master",
        "philippfrenzel/yii2fullcalendar": "*",
        "dmstr/yii2-adminlte-asset": "*"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}

```

**Comment by philippfrenzel** [comment]
pls. check 

composer self-update
and 
francois../composer-asset is the latest

then pls. remove the vendor folder and 

composer.phar update

had the same issue... should work fine after it!

**Comment by fruppel** [comment]
Okay that worked :-) Thank you!

**Comment by wilkoli** [comment]
Hi,

I installed the package yii2fullcalendar via composer but when I render the view i get this error

The file or directory to be published does not exist: project-name/vendor/bower/fullcalendar/dist

I see that inside of vendor/bower/yii2fullcalendar/ i don't have the "dist" folder. this means that i don't do assets's registration (js & css) correctly? I try to write composer.phar self-update and then composer.phar update but nothing changes. some idea? Thanks!

**Comment by philippfrenzel** [comment]
Hi @wilkoli, sorry to tell, but it looks like you have to delete the whole vendor folder, as the composer plugin who manages the assets keeps a "cached" version which will not rewrite the assets into the dist bower folder. Pls. let me know if this works? Thanks Phil

**Comment by wilkoli** [comment]
Hi @philippfrenzel 

I remove again vendor folder and then composer.phar self-update and later, composer.phar update. I get the vendor folder with all the packages. i am with yii2 advanced project and i don't know how to manage the cache through the assets. Is there some config step after downloading the packages? In symfony2.x you can delete cache of dev enviroment with the command "php app/console cache:clear --env=dev" but I don't know how yii2 manages with config's issues and specially with assets.

Shell --> inside vendor/bower
drwxr-xr-x  14 webscoming  staff   476 27 ene 16:06 ace-builds
drwxr-xr-x  12 webscoming  staff   408 27 ene 16:06 bootstrap
drwxr-xr-x   6 webscoming  staff   204 27 ene 16:08 fullcalendar
drwxr-xr-x   6 webscoming  staff   204 27 ene 16:05 jquery
drwxr-xr-x  14 webscoming  staff   476 27 ene 16:06 jquery-ui
drwxr-xr-x   6 webscoming  staff   204 27 ene 16:05 jquery.inputmask
drwxr-xr-x  14 webscoming  staff   476 27 ene 16:08 moment

➜  bower git:(master) ✗ cd fullcalendar 
➜  fullcalendar git:(master) ✗ ls -la
drwxr-xr-x  12 webscoming  staff    408 27 ene 16:08 ..
-rw-r--r--   1 webscoming  staff    757 12 ene 02:08 bower.json
-rw-r--r--   1 webscoming  staff  34051 12 ene 02:08 changelog.md
-rw-r--r--   1 webscoming  staff   1053 12 ene 02:08 license.txt
-rw-r--r--   1 webscoming  staff    671 12 ene 02:08 readme.md

As you can see, there is no dist folder with the assets.

I have the same config on composer.json
...
"minimum-stability": "dev",
	"require": {
	"php": ">=5.4.0",
        "ext-intl": "*",
        "ext-mcrypt": "*",
		"yiisoft/yii2": "~2.0",
		"yiisoft/yii2-bootstrap": "*",
		"yiisoft/yii2-swiftmailer": "*",
		"yiisoft/yii2-authclient": "*",
		"asofter/yii2-imperavi-redactor": "*",
		"yiisoft/yii2-jui": "*",
        "mihaildev/yii2-elfinder": "*",
        "trntv/yii2-aceeditor": "*",
        "trntv/systeminfo": "*",
        "trntv/yii2-file-kit": "*",
        "trntv/yii2-bootstrap-datetimepicker": "dev-master",
        "kartik-v/yii2-detail-view": "*",
        "phpoffice/phpexcel": "dev-develop",
        "kartik-v/yii2-widget-alert": "*",
        "miloschuman/yii2-highcharts-widget": "dev-master",
        "robregonm/yii2-pdf": "dev-master",
        "2amigos/yii2-highcharts-widget": "*",
        "kartik-v/yii2-mpdf": "*",
        "himiklab/yii2-search-component-v2": "*",
        "kartik-v/yii2-widget-select2": "*",
        "intervention/image": "dev-master",
        "kartik-v/yii2-widgets": "*",
        "kartik-v/dependent-dropdown": "dev-master",
        "kartik-v/yii2-widget-datepicker": "*",
        "thiagotalma/yii2-fullcalendar": "*",
        "philippfrenzel/yii2fullcalendar": "*"
       
	},
	"require-dev": {
		"yiisoft/yii2-debug": "*",
        "trntv/yii2-debug-xhprof": "*",
		"yiisoft/yii2-gii": "*",
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-faker": "*",
        "codeception/codeception": "2.*",
        "yiisoft/yii2-swiftmailer": "*"
	},
    "suggest": {
        "trntv/yii2-deploy": "*"
    },
	"config": {
		"process-timeout": 1800
	},
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "frontend/runtime": "0777",
                    "backend/runtime": "0777",
                    "console/runtime": "0777",
                    "frontend/web/assets": "0777",
                    "backend/web/assets": "0777",
                    "storage": "0777",
                    "environments/local/backend/yii": "0755",
                    "environments/local/frontend/yii": "0755",
                    "environments/local/console/yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "frontend/config/main.php",
                "backend/config/main.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }

I will look at the issue of "assets" but thanks anyway Phil.

**Comment by philippfrenzel** [comment]
sorry this didn't solve it... I'll try with a blank setup and come back to you1 - you are always welcome;)

**Comment by philippfrenzel** [comment]
@wilkoli which version of francois composer asset plugin are you running? need the latest version! That's important!

**Comment by wilkoli** [comment]
fxp/composer-asset-plugin           1.0.x-dev c4ff35c   NPM/Bower Dependency Manager for Composer

**Comment by philippfrenzel** [comment]
ok, so you have the latest version... I just setup the advanced up and send you the info...

**Comment by philippfrenzel** [comment]
@wilkoli i build the advanced app from "zero" and everything works fine for me:
```
"minimum-stability": "dev",
    "require": {
        "philippfrenzel/yii2fullcalendar":"*",
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*"
    },
```
will end up in:

![screenshot 2015-01-28 16 20 56](https://cloud.githubusercontent.com/assets/2319890/5940213/ad3e3e4e-a709-11e4-8cb1-62789758bbcd.png)

**Comment by wilkoli** [comment]
@philippfrenzel 

I have solved the config error. thanks for the support! :)

**Comment by philippfrenzel** [comment]
you are welcome and I'm happy you figured out how to manage it!
Cheers Philipp

**Comment by eramudeep** [comment]
its weird.

**i fixed it by creating directories manually**
