### ISSUE TITLE
The file or directory to be published does not exist

### ISSUE THREAD

**Issue by firstau** [philippfrenzel/yii2fullcalendar#40]
just installed the fullcalender widget and run into an error which is the fullcalender files are installed in bower-asset folder and the widget is looking at bower folder. after manual copy the files from bower-asset folder to bower folder, the widget works fine.

**Comment by philippfrenzel** [comment]
did you install the composer bower plugin?

**Comment by firstau** [comment]
No, I didn't install the composer bower plugin. But I installed other extensions and it may led to install the bower-asset folder.
the calendar works good now after the files moved and shows the events from database. Just one problem which is unable to get the event id by click the event on calendar. The "eventClick:" callback doesn't work (refer to http://fullcalendar.io/docs/mouse/eventClick/ ) after render the calendar by <?= \yii2fullcalendar\yii2fullcalendar::widget(array(
      'events'=> $events,
  ));
or 'ajaxEvents' => Url::to(['/timetrack/default/jsoncalendar'])

Could you please let me know the best way to get the event id after the calendar rendered?
Thanks in advance!

**Comment by philippfrenzel** [comment]
Hi, I will take a look in about 8 hours - busy until then ;)

**Comment by philippfrenzel** [comment]
Hi, did you manage to solve this issue? I suggest you enable the select and selecthelper and then you'll get fired the information you are looking for!
