### ISSUE TITLE
Print agendaWeek not working

### ISSUE THREAD

**Issue by le-o** [philippfrenzel/yii2fullcalendar#45]
When i try to print the calendar in agendaWeek mode, no events are display.

<?= yii2fullcalendar\yii2fullcalendar::widget([
        'clientOptions' => [
            'lang' => 'fr',
            'defaultView' => 'agendaWeek',
            'weekNumbers' => true,
            'defaultDate' => date('Y-m-d'),
            'eventTimeFormat' => 'H:mm',
            'scrollTime' => '08:00:00',
            'aspectRatio' => 1.6,
            'allDaySlot' => false,
            'eventLimit' => 3,
        ],
        'options' => [
            'id' => 'myCalendar',
        ],
        'header' => [
            'center'=>'title',
            'left'=>'prev,next today', 
            'right'=>'agendaDay,agendaWeek,month'
        ],
        'eventRender' => 'function(event, element) {
            element.find(\'.fc-title\').append("<br/><br/><i>" + event.description + "</i>");
        } ',
        'ajaxEvents' => yii\helpers\Url::to(['/jsoncalendar'])
    ]); ?>

PS: in month view, all is working well.

**Comment by philippfrenzel** [comment]
hmm - that's interesting - do you pass time's in your events or are they all full day?

**Comment by le-o** [comment]
Both.
It seems that a full day event print properly.
Before posting an issue, i try your demo (http://yii2fullcalendar.beeye.org/) and found out that the same bug is present.

**Comment by philippfrenzel** [comment]
ok, I guess I found the reason will fix it within the next 48 hours ;)

**Comment by le-o** [comment]
Hell Yeah !
Can you share what you found out ? I try by my side without success...

**Comment by philippfrenzel** [comment]
Ok, I need to switch to the minified css. It's funny because the minified version has other pre classes then the none minified... Will investigate in this - for now I will switch to the min version ... ;) Pls. let me know if that worked for you?

**Comment by le-o** [comment]
You put me on a track !
Use the minified version don't work for me. But it help me to understand that it is a css thing.
I add the standard css to PrintAsset.php like this 
`/**
     * [$css description]
     * @var array
     */
    public $css = [
        'fullcalendar.css',
        'fullcalendar.print.css'
    ];`

Now it works like a charm !
Thank you for your work and your reactivity.

**Comment by philippfrenzel** [comment]
I'm happy it worked out, still will investigate, as the core asset depends on the print asset which should have worked from the beginning! Thanks for sharing solution!
