### ISSUE TITLE
Click event error

### ISSUE THREAD

**Issue by 3dgroup** [philippfrenzel/yii2fullcalendar#46]
fullcalendar.js:9276 Uncaught TypeError: options[name].apply is not a function. Cant see to avoid this error. Here is the code

\yii2fullcalendar\yii2fullcalendar::widget(array(
    'options' => [
        'lang' => 'en-GB',
    //... more options to be defined here!
    ],
    'clientOptions' => [
        'eventClick' => "eventClick: function(calEvent, jsEvent, view) {
        window.location = 'http://www.domain.com?start=' + calEvent.start;

    }"],
    'events' => $events,
));

**Comment by philippfrenzel** [comment]
can you pls wrap it into JSExpression (yii\helpers\) and check if it's working?

**Comment by 3dgroup** [comment]
Ahh! That works thanks

**Comment by philippfrenzel** [comment]
perfect! I'll close it;)
