### ISSUE TITLE
Can not get the Callback functions such as eventClick, eventResize

### ISSUE THREAD

**Issue by firstau** [philippfrenzel/yii2fullcalendar#47]
Hi Phil,
I cannot get the event callback functions work. Could you please tell me how to implement the eventClick, eventResize after the calendar is rendered?

I use this in index.php  <?=  \yii2fullcalendar\yii2fullcalendar::widget(array(
             'events' => $events,?>
and the events show in the calendar properly. But the calendar events will not show on calendar when I add the following JS code from the link http://fullcalendar.io/docs/mouse/eventClick/:

$('#calendar').fullCalendar({
    eventClick: function(calEvent, jsEvent, view) {

```
    alert('Event: ' + calEvent.title);
    alert('Coordinates: ' + jsEvent.pageX + ',' + jsEvent.pageY);
    alert('View: ' + view.name);

    // change the border color just for fun
    $(this).css('border-color', 'red');

}
```

});

**Comment by philippfrenzel** [comment]
Hi, I guess I'll have tp update the version of full calendar... let me try today and I'll come back to you

**Comment by eothein** [comment]
Is there any news on this front? I also want to be able to manipulate the calendar.

**Comment by philippfrenzel** [comment]
Hi,

I just wrote a quiet complex solution using the calendar and events and it's working -> you should encapsule the function into \yii\helpers\JSExpression()

Pls. let me know if this solves your issue
