### ISSUE TITLE
ReflectionException Class yii\jui\JuiAsset does not exist

### ISSUE THREAD

**Issue by pawaramitr** [philippfrenzel/yii2fullcalendar#49]
ReflectionException
Class yii\jui\JuiAsset does not exist
solution i found ->
 In file [VandorDir]/philippfrenzel\yii2fullcalendar\CoreAsset.php change public $depends = ['yii\jui\JuiAsset']; in to public $depends = ['yii\web\YiiAsset']; ...will work fine﻿

**Comment by pawaramitr** [comment]
but i think this is not accurate solution... something else is wrong

**Comment by philippfrenzel** [comment]
Hmm, I will take a look at this - so maybe due to yii2 development the asset dependencies have changed?! Which version of yii are you using?

**Comment by yingzzai** [comment]
How is this problem solved? I also met, please give some ideas, thank you

**Comment by philippfrenzel** [comment]
Hi I guess this has to do with your Yii2 Asset configuration - have you tried adding the dependeny of JUI within you AppAsset.php?

**Comment by yingzzai** [comment]
I've solved this problem.

I add this sentence to web.php,

'aliases' => [ 
                     '@yii/jui' => '@vendor/yiisoft/yii2-jui',
	           ],

Thank you very much for your advice.

**Comment by philippfrenzel** [comment]
Changed months ago - closing this issue
