### ISSUE TITLE
Invalid Parameter – yii\base\InvalidParamException

### ISSUE THREAD

**Issue by Migo2468** [philippfrenzel/yii2fullcalendar#5]
Hi I have a problem with component when I try load a widget i heve errors:
The file or directory to be published does not exist: /volume1/web/Migo/advanced/app/vendor/bower/fullcalendar/dist

1. in /volume1/web/Migo/advanced/app/vendor/yiisoft/yii2/web/AssetManager.php at line 385
line 385: throw new InvalidParamException("The file or directory to be published does not exist: $path");

I try install this component in Phundament 4.

**Comment by philippfrenzel** [comment]
Hi, pls ensure composer plugin installed?

**Comment by philippfrenzel** [comment]
Just tested it with ph4 and works... As mentioned, pls ensure composer-asset plugin.. If needed clear your vendor folder and run composer update again

**Comment by Migo2468** [comment]
My composer.json have: 
"require": {
    "php": ">=5.4.0",
    "vlucas/phpdotenv": "1.*",
    "yiisoft/yii2-composer": "*",
    "yiisoft/yii2": "2.0.*",
    "yiisoft/yii2-bootstrap": "2.*",
    "yiisoft/yii2-swiftmailer": "2.*",
    "dektrium/yii2-user": "0.9.*",
    "mikehaertl/php-shellcommand": "1.*",
    "dmstr/yii2-app-command": "dev-master",
    "dmstr/yii2-migrate-command": "*",
    "dmstr/yii2-adminlte-asset": "*",
    "dmstr/yii2-log": "dev-master",
    "schmunk42/yii2-packaii": "dev-master",
    "schmunk42/yii2-markdocs-module": "dev-master",
    "philippfrenzel/yii2fullcalendar":"*",
    "sintret/yii2-chat-adminlte": "dev-master"
  },

<b>I update composer, and I have:</b> 
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing yiisoft/yii2-composer (2.0.2)               
    Loading from cache

  - Installing dmstr/yii2-app-command (dev-master 99ad4f5)
    Cloning 99ad4f5fc5227aa3415b20b991deda6254e65a5f

  - Installing dmstr/yii2-migrate-command (0.1.0)
    Loading from cache

  - Installing bower-asset/font-awesome (v4.3.0)
    Loading from cache

  - Installing bower-asset/jquery (2.1.3)
    Loading from cache

  - Installing bower-asset/bootstrap (v3.3.2)
    Loading from cache

  - Installing bower-asset/admin-lte (1.3.1)
    Loading from cache

  - Installing bower-asset/yii2-pjax (v2.0.2)
    Loading from cache

  - Installing bower-asset/punycode (v1.3.2)
    Loading from cache

  - Installing bower-asset/jquery.inputmask (3.1.61)
    Downloading: 100%         

  - Installing cebe/markdown (1.0.1)
    Loading from cache

  - Installing ezyang/htmlpurifier (v4.6.0)
    Loading from cache

  - Installing yiisoft/yii2 (2.0.2)
    Loading from cache

  - Installing cebe/yii2-gravatar (1.1)
    Loading from cache

  - Installing yiisoft/yii2-bootstrap (2.0.2)
    Loading from cache

  - Installing dmstr/yii2-adminlte-asset (0.1.0)
    Loading from cache

  - Installing dmstr/yii2-log (dev-master 8fc081b)
    Cloning 8fc081bf19f8a0ab8bcbd450b4aaf99d6c9abfc1

  - Installing yiisoft/yii2-debug (2.0.2)
    Loading from cache

  - Installing 2amigos/yii2-pjax-filter-behavior (0.1.0)
    Loading from cache

  - Installing 2amigos/yii2-arrayquery-component (0.1.1)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.6.4)
    Loading from cache

  - Installing guzzle/guzzle (v3.8.1)
    Loading from cache

  - Installing 2amigos/yii2-packagist-component (0.1.1)
    Loading from cache

  - Installing schmunk42/yii2-packaii (dev-master 97b0368)
    Cloning 97b0368f4526a283e4f137c691b0cf9f7befe354

  - Installing schmunk42/yii2-markdocs-module (dev-master bb2d65b)
    Cloning bb2d65bc83a43fcc5a5238561255ca920d3a035d

  - Installing kartik-v/yii2-helpers (v1.3.0)
    Loading from cache

  - Installing sintret/yii2-chat-adminlte (dev-master f4890cd)
    Cloning f4890cd06e904d38b3e1d724fcfc4222d278aec8

  - Installing squizlabs/php_codesniffer (1.5.6)
    Loading from cache

  - Installing yiisoft/yii2-coding-standards (2.0.0)
    Loading from cache

  - Installing vlucas/phpdotenv (v1.1.0)
    Loading from cache

  - Installing yiisoft/yii2-authclient (2.0.2)
    Loading from cache

  - Installing swiftmailer/swiftmailer (v5.3.1)
    Loading from cache

  - Installing yiisoft/yii2-swiftmailer (2.0.2)
    Loading from cache

  - Installing dektrium/yii2-user (v0.9.2)
    Loading from cache

  - Installing mikehaertl/php-shellcommand (1.0.4)
    Loading from cache

  - Installing bower-asset/moment (2.9.0)
    Loading from cache

  - Installing bower-asset/fullcalendar (v2.2.6)
    Loading from cache

  - Installing bower-asset/jquery-ui (1.11.2)
    Loading from cache

  - Installing yiisoft/yii2-jui (2.0.2)
    Loading from cache

  - Installing philippfrenzel/yii2fullcalendar (2.2.6)
    Loading from cache

  - Installing phpspec/php-diff (v1.0.2)
    Loading from cache

  - Installing fzaninotto/faker (v1.4.0)
    Loading from cache

  - Installing yiisoft/yii2-faker (2.0.2)
    Loading from cache

  - Installing yiisoft/yii2-codeception (2.0.2)
    Loading from cache

  - Installing mikevanriel/text-to-latex (1.0.0)
    Loading from cache

  - Installing cebe/markdown-latex (1.0.0)
    Loading from cache

  - Installing cebe/js-search (0.9.1)
    Loading from cache

  - Installing nikic/php-parser (v0.9.5)
    Loading from cache

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Loading from cache

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing phpdocumentor/reflection (1.0.7)
    Loading from cache

  - Installing yiisoft/yii2-apidoc (2.0.2)
    Loading from cache

  - Installing bower-asset/typeahead.js (v0.10.5)
    Loading from cache

  - Installing yiisoft/yii2-gii (2.0.2)
    Loading from cache

  - Installing schmunk42/yii2-giiant (0.2.0)
    Loading from cache

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
squizlabs/php_codesniffer suggests installing phpunit/php-timer (dev-master)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
Writing lock file
Generating autoload files

<b>There are no errors in update but in page I have the same error.</b>

**Comment by philippfrenzel** [comment]
I see you are loading from cache... pls. delete your vendor folder and then rerun the composer update... before, pls check that you made the composer self-update and moved to the latest version to

**Comment by Migo2468** [comment]
<b>I use comand: </b>
ssh> php composer.phar clearcache
Clearing cache (cache-dir): /volume1/homes/admin/.composer/cache
Clearing cache (cache-files-dir): /volume1/homes/admin/.composer/cache/files
Clearing cache (cache-repo-dir): /volume1/homes/admin/.composer/cache/repo
Clearing cache (cache-vcs-dir): /volume1/homes/admin/.composer/cache/vcs
All caches cleared.

<b>Next:</b>
Kowliman> php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing yiisoft/yii2-composer (2.0.2)               
    Downloading: 100%         

  - Installing dmstr/yii2-app-command (dev-master 99ad4f5)
    Cloning 99ad4f5fc5227aa3415b20b991deda6254e65a5f

  - Installing dmstr/yii2-migrate-command (0.1.0)
    Downloading: 100%         

  - Installing bower-asset/font-awesome (v4.3.0)
    Downloading: 100%         

  - Installing bower-asset/jquery (2.1.3)
    Downloading: 100%         

  - Installing bower-asset/bootstrap (v3.3.2)
    Downloading: 100%         

  - Installing bower-asset/admin-lte (1.3.1)
    Downloading: 100%         

  - Installing bower-asset/yii2-pjax (v2.0.2)
    Downloading: 100%         

  - Installing bower-asset/punycode (v1.3.2)
    Downloading: 100%         

  - Installing bower-asset/jquery.inputmask (3.1.61)
    Downloading: 100%         

  - Installing cebe/markdown (1.0.1)
    Downloading: 100%         

    Skipped installation of bin bin/markdown for package cebe/markdown: name conflicts with an existing file
  - Installing ezyang/htmlpurifier (v4.6.0)
    Downloading: 100%         

  - Installing yiisoft/yii2 (2.0.2)
    Downloading: 100%         

    Skipped installation of bin yii for package yiisoft/yii2: name conflicts with an existing file
  - Installing cebe/yii2-gravatar (1.1)
    Downloading: 100%         

  - Installing yiisoft/yii2-bootstrap (2.0.2)
    Downloading: 100%         

  - Installing dmstr/yii2-adminlte-asset (0.1.0)
    Downloading: 100%         

  - Installing dmstr/yii2-log (dev-master 8fc081b)
    Cloning 8fc081bf19f8a0ab8bcbd450b4aaf99d6c9abfc1

  - Installing yiisoft/yii2-debug (2.0.2)
    Downloading: 100%         

  - Installing 2amigos/yii2-pjax-filter-behavior (0.1.0)
    Downloading: 100%         

  - Installing 2amigos/yii2-arrayquery-component (0.1.1)
    Downloading: 100%         

  - Installing symfony/event-dispatcher (v2.6.4)
    Downloading: 100%         

  - Installing guzzle/guzzle (v3.8.1)
    Downloading: 100%         

  - Installing 2amigos/yii2-packagist-component (0.1.1)
    Downloading: 100%         

  - Installing schmunk42/yii2-packaii (dev-master 97b0368)
    Cloning 97b0368f4526a283e4f137c691b0cf9f7befe354

  - Installing schmunk42/yii2-markdocs-module (dev-master bb2d65b)
    Cloning bb2d65bc83a43fcc5a5238561255ca920d3a035d

  - Installing kartik-v/yii2-helpers (v1.3.0)
    Downloading: 100%         

  - Installing sintret/yii2-chat-adminlte (dev-master f4890cd)
    Cloning f4890cd06e904d38b3e1d724fcfc4222d278aec8

  - Installing squizlabs/php_codesniffer (1.5.6)
    Downloading: 100%         

    Skipped installation of bin scripts/phpcs for package squizlabs/php_codesniffer: name conflicts with an existing file
  - Installing yiisoft/yii2-coding-standards (2.0.0)
    Downloading: 100%         

  - Installing vlucas/phpdotenv (v1.1.0)
    Downloading: 100%         

  - Installing yiisoft/yii2-authclient (2.0.2)
    Downloading: 100%         

  - Installing swiftmailer/swiftmailer (v5.3.1)
    Downloading: 100%         

  - Installing yiisoft/yii2-swiftmailer (2.0.2)
    Downloading: 100%         

  - Installing dektrium/yii2-user (v0.9.2)
    Downloading: 100%         

  - Installing mikehaertl/php-shellcommand (1.0.4)
    Downloading: 100%         

  - Installing bower-asset/moment (2.9.0)
    Downloading: 100%         

  - Installing bower-asset/fullcalendar (v2.2.6)
    Downloading: 100%         

  - Installing bower-asset/jquery-ui (1.11.2)
    Downloading: 100%         

  - Installing yiisoft/yii2-jui (2.0.2)
    Downloading: 100%         

  - Installing philippfrenzel/yii2fullcalendar (2.2.6)
    Downloading: 100%         

  - Installing phpspec/php-diff (v1.0.2)
    Downloading: 100%         

  - Installing fzaninotto/faker (v1.4.0)
    Downloading: 100%         

  - Installing yiisoft/yii2-faker (2.0.2)
    Downloading: 100%         

  - Installing yiisoft/yii2-codeception (2.0.2)
    Downloading: 100%         

  - Installing mikevanriel/text-to-latex (1.0.0)
    Downloading: 100%         

  - Installing cebe/markdown-latex (1.0.0)
    Downloading: 100%         

    Skipped installation of bin bin/markdown-latex for package cebe/markdown-latex: name conflicts with an existing file
  - Installing cebe/js-search (0.9.1)
    Downloading: 100%         

    Skipped installation of bin bin/jsindex for package cebe/js-search: name conflicts with an existing file
  - Installing nikic/php-parser (v0.9.5)
    Downloading: 100%         

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Downloading: 100%         

  - Installing psr/log (1.0.0)
    Downloading: 100%         

  - Installing phpdocumentor/reflection (1.0.7)
    Downloading: 100%         

  - Installing yiisoft/yii2-apidoc (2.0.2)
    Downloading: 100%         

    Skipped installation of bin apidoc for package yiisoft/yii2-apidoc: name conflicts with an existing file
  - Installing bower-asset/typeahead.js (v0.10.5)
    Downloading: 100%         

  - Installing yiisoft/yii2-gii (2.0.2)
    Downloading: 100%         

  - Installing schmunk42/yii2-giiant (0.2.0)
    Downloading: 100%         

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
squizlabs/php_codesniffer suggests installing phpunit/php-timer (dev-master)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
Generating autoload files


<b>In page I have the same error.</b>

**Comment by philippfrenzel** [comment]
ok, this is crazy... I will try again with the latest phundament installation and give you feedback in about 15 min

**Comment by Migo2468** [comment]
Thanks for all, I wait.

**Comment by philippfrenzel** [comment]
Just so we are talking about the same here:

created empty folder and ran:

composer create-project --stability=beta phundament/app

then edited composer.json and added:

"philippfrenzel/yii2fullcalendar" : "*"
![screenshot 2015-02-06 17 07 07](https://cloud.githubusercontent.com/assets/2319890/6082552/9cff3c0c-ae22-11e4-8549-c20896642222.png)

at the end after that I run composer update (have it globaly installed;))

So, as you can see, the files have been generated...

![screenshot 2015-02-06 17 09 13](https://cloud.githubusercontent.com/assets/2319890/6082603/f1899452-ae22-11e4-8c9b-3cfaa7459e86.png)

now I have to setup the .env file, to have a running db connection
> cp .env-dist .env

I use nano to edit the file...

after all works fine, i run the commandline php yii app/setup

in the index file i add straight below the header

<div class="container">
        <?= yii2fullcalendar\yii2fullcalendar::widget([
          'options' => [
            'lang' => 'de',
            'class' => 'fullcalendar'
          ]
        ]);
        ?>
    </div>

and end up with:

![screenshot 2015-02-06 17 17 00](https://cloud.githubusercontent.com/assets/2319890/6082772/0626084a-ae24-11e4-8d06-b0afc43007e0.png)

And it works... so what I think, is that your alias management is broken...:(
normally this should be set by yii2/base/application.php so I think you changed your vendor folder, as bower depends on that one...

cheers Philipp

**Comment by Migo2468** [comment]
I do not know, I instal in new folder phundament then edit composer.json and add your code. Next update, and it does not work. The folder vendor/bower/fullcalendar/dist does not exist. I do not know why in my server it does not work.

**Comment by philippfrenzel** [comment]
can you pls send me your php -v and a php info? I'm pretty it's not a matter of your code anymore... looks like your enviroment PHP could be the issue....

**Comment by Migo2468** [comment]
PHP 5.5.21 (cli) (built: Feb  2 2015 21:00:58) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies

http://jsfiddle.net/yx3d5ose/embedded/result/

**Comment by philippfrenzel** [comment]
Thanks! So after checking your conf. I just have a difference within the fact that you are using zend oocache... which I don't and it seems like you are working with "symlinks"? So I think that

/volume1/web/Migo/advanced/app/vendor/bower/fullcalendar/dist

is not the place where all your bower packages are getting packed...
where e.g. do you find the bootstrap or admin-lte bower files?

**Comment by Migo2468** [comment]
I think bootrstrap have all file in: 
/volume1/web/Migo/advanced/app/vendor/bower/bootstrap/dist

Here are screen:
![zaznaczenie_001](https://cloud.githubusercontent.com/assets/3847457/6091658/1878e010-aeb7-11e4-923a-4865e2764be1.png)
![zaznaczenie_002](https://cloud.githubusercontent.com/assets/3847457/6091659/187a0008-aeb7-11e4-9569-e6eab79a90cc.png)
![zaznaczenie_003](https://cloud.githubusercontent.com/assets/3847457/6091660/1879fe0a-aeb7-11e4-99a9-382993dc91ca.png)

**Comment by philippfrenzel** [comment]
ok, that's super crazy... I don't understand why it's not getting downloaded... I had this issue with people using an "older" version of "fxp/composer-asset-plugin:~1.0" ... what is your version here?

>php composer.phar show -i

I have: fxp/composer-asset-plugin    dev-master 4b97e5c NPM/Bower Dependency Manager for Composer

**Comment by Migo2468** [comment]
ssh> php composer.phar show -i
2amigos/yii2-arrayquery-component 0.1.1              Yii2 component that allows...
2amigos/yii2-packagist-component  0.1.1              Yii 2 Packagist API extens...
2amigos/yii2-pjax-filter-behavior 0.1.0              Yii2 filters that filters ...
bower-asset/admin-lte             1.3.1              
bower-asset/bootstrap             v3.3.2             The most popular front-end...
bower-asset/font-awesome          v4.3.0             Font Awesome
bower-asset/fullcalendar          v2.2.6             Full-sized drag & drop eve...
bower-asset/jquery                2.1.3              
bower-asset/jquery-ui             1.11.2             
bower-asset/jquery.inputmask      3.1.61             jquery.inputmask is a jque...
bower-asset/moment                2.9.0              
bower-asset/punycode              v1.3.2             
bower-asset/typeahead.js          v0.10.5            
bower-asset/yii2-pjax             v2.0.2             
cebe/js-search                    0.9.1              A client side search engin...
cebe/markdown                     1.0.1              A super fast, highly exten...
cebe/markdown-latex               1.0.0              A super fast highly extens...
cebe/yii2-gravatar                1.1                Gravatar Widget for Yii 2
dektrium/yii2-user                v0.9.2             Flexible user registration...
dmstr/yii2-adminlte-asset         0.1.0              Backend theme for Yii2 Fra...
dmstr/yii2-app-command            dev-master 99ad4f5 Console command for Yii 2 ...
dmstr/yii2-log                    dev-master 8fc081b SyslogTarget writes log to...
dmstr/yii2-migrate-command        0.1.0              Console Migration Command ...
ezyang/htmlpurifier               v4.6.0             Standards compliant HTML f...
fzaninotto/faker                  v1.4.0             Faker is a PHP library tha...
guzzle/guzzle                     v3.8.1             Guzzle is a PHP HTTP clien...
kartik-v/yii2-helpers             v1.3.0             A collection of useful hel...
mikehaertl/php-shellcommand       1.0.4              An object oriented interfa...
mikevanriel/text-to-latex         1.0.0              A converter class that con...
nikic/php-parser                  v0.9.5             A PHP parser written in PHP
philippfrenzel/yii2fullcalendar   2.2.6              Yii2 fullcalendar Widgets
phpdocumentor/reflection          1.0.7              Reflection library to do S...
phpdocumentor/reflection-docblock 2.0.4              
phpspec/php-diff                  v1.0.2             A comprehensive library fo...
psr/log                           1.0.0              Common interface for loggi...
schmunk42/yii2-giiant             0.2.0              Gii CRUD generator for Yii...
schmunk42/yii2-markdocs-module    dev-master bb2d65b Renders markdown files fro...
schmunk42/yii2-packaii            dev-master 97b0368 Yii2 Framework Web-UI for ...
sintret/yii2-chat-adminlte        dev-master f4890cd Yii2 extension for Chat pl...
squizlabs/php_codesniffer         1.5.6              PHP_CodeSniffer tokenises ...
swiftmailer/swiftmailer           v5.3.1             Swiftmailer, free feature-...
symfony/event-dispatcher          v2.6.4             Symfony EventDispatcher Co...
thiagotalma/yii2-fullcalendar     2.0.0              Widget for Yii Framework 2...
vlucas/phpdotenv                  v1.1.0             Loads environment variable...
yiisoft/yii2                      2.0.2              Yii PHP Framework Version 2
yiisoft/yii2-apidoc               2.0.2              API Documentation generato...
yiisoft/yii2-authclient           2.0.2              External authentication vi...
yiisoft/yii2-bootstrap            2.0.2              The Twitter Bootstrap exte...
yiisoft/yii2-codeception          2.0.2              The Codeception integratio...
yiisoft/yii2-coding-standards     2.0.0              Yii PHP Framework Version ...
yiisoft/yii2-composer             2.0.2              The composer plugin for Yi...
yiisoft/yii2-debug                2.0.2              The debugger extension for...
yiisoft/yii2-faker                2.0.2              Fixture generator. The Fak...
yiisoft/yii2-gii                  2.0.2              The Gii extension for the ...
yiisoft/yii2-jui                  2.0.2              The Jquery UI extension fo...
yiisoft/yii2-swiftmailer          2.0.2              The SwiftMailer integratio...

**Comment by philippfrenzel** [comment]
Hi I don't see the fxp plugin?

**Comment by Migo2468** [comment]
I delete vendor folder, add 
"fxp/composer-asset-plugin": "2.0.*@dev",
to composer.json, clear cache and update. But in folder bower/fullcalendar has not a folder dist. 

I don't know why.

**Comment by philippfrenzel** [comment]
Fxp is only available as 1. Version?

**Comment by philippfrenzel** [comment]
@Migo2468 can you pls. try to upgrade, should work now...

**Comment by Migo2468** [comment]
I try today and give you feedback.

**Comment by Migo2468** [comment]
yeah, 

When i add comend in terminal: 
php composer.phar global require "fxp/composer-asset-plugin:~1.0"


All fine work, Thank you @philippfrenzel for all.

**Comment by philippfrenzel** [comment]
you are welcome!
