### ISSUE TITLE
How to add onclick modal for Event in calendar

### ISSUE THREAD

**Issue by ViaJasmine** [philippfrenzel/yii2fullcalendar#50]
I am trying to add a feature where when user clicks the event, a modal will pop with details of the Event. How to do this?

**Comment by philippfrenzel** [comment]
pls. check the fullcalendar.io docs to implement this

**Comment by philippfrenzel** [comment]
Quick hint: 

if you wanna make a pop up, pls. add to the clientOptions an "select" handler and include a JS into your app which is kind of:
```
function(start,end){
 ....
}
```
