### ISSUE TITLE
Depending on your CoreAsset

### ISSUE THREAD

**Issue by eothein** [philippfrenzel/yii2fullcalendar#51]
Dear Philipp
I'm trying to add my javascipt file to manipulate the calendar in de browser. I have created an Asset which should depend on your Asset (CoreAsset I presume). Only when I add the dependancy I receive the error:

> Unknown Class – yii\base\UnknownClassException
> Unable to find 'app\vendor\philippfrenzel\yii2fullcalendar\CoreAsset' in file: H:\Equality\horizonmanagerv2/vendor/philippfrenzel/yii2fullcalendar/CoreAsset.php. Namespace missing?

My AssetBundle is as follows:
`<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\assets;

use yii\web\AssetBundle;

/**
 * @author Jens Buysse <jens.buysse@gmail.com>
 * @since 2.0
 */
class PrijszettingAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
        
    ];
    public $js = [
        'js/prijszetting.js'
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'app\vendor\philippfrenzel\yii2fullcalendar\CoreAsset'
        
    ];
}`

**Comment by philippfrenzel** [comment]
Hi, you have to replace:

'yii\web\YiiAsset',
'app\vendor\philippfrenzel\yii2fullcalendar\CoreAsset'

];

with:

'yii\web\YiiAsset',
'\yii2fullcalendar\CoreAsset'

];

Best Philipp

**Comment by eothein** [comment]
Dear Philipp, this works indeed - Thank you! Can you provide me the reference or the information why this helps the problem?

Kind regards
Jens Buysse

**Comment by philippfrenzel** [comment]
Hi, you need to check the composer file of the extension you load and see how it's get resolved into the namespace.
