### ISSUE TITLE
javascript error using onClick callback

### ISSUE THREAD

**Issue by a2dgroup** [philippfrenzel/yii2fullcalendar#53]
Hi,
thank you for making this plugin. 
The calendar give me an error when trying to use the onclick event on the events in this way:

`<?= \yii2fullcalendar\yii2fullcalendar::widget(array(
      'events'=> $events,
      'clientOptions' => [
            'lang' => 'it',
            'defaultView' => 'agendaWeek',
            'minTime' => "08:00:00",
            'maxTime' => "24:00:00",
            'eventClick' => 'function(){alert(1);}',
        ]
  ));`

Instead of alert(1) message I get this javascript error:
`fullcalendar.js:9873 Uncaught TypeError: options[name].apply is not a function`

Thank You

Alessandro

**Comment by philippfrenzel** [comment]
Hi,

you should use the select instead of eventClick - pls. see #54
