### ISSUE TITLE
hiddenDays doesn't work

### ISSUE THREAD

**Issue by Velheorus** [philippfrenzel/yii2fullcalendar#54]
Hello!
Thank you for this plugin.
I have some questions to you:
**1)** Can you please provide **"hiddenDays"** option in your fullcalendar? Because only "weekends" works;
**2)** How can i enable "eventClick" in yii2, because i don't know a normal way to open "view" in CRUD without it?
Thank you!

**Comment by philippfrenzel** [comment]
Hi,

1) I will add it this evening;)
2) it's the select property of the calendar

You can get it to run like:

`
<?php 

$timemanager = Url::toRoute('/timeschedule/timeschedule-detail/json-manage',true);

$JSEventSelect = <<<EOF
function(start, end) {
    event.preventDefault();
 	var tsStart = start.toString(); 	
 	var tsEnd = end.toString();
 	var modelId = $('#timeschedule-id').data('id');
   	
   	var request = $.ajax({
   		url : '$timemanager',
   		format : 'JSON',
   		data : {
   			'action' : 'CREATE',
   			'tsStart' : tsStart,
      		'tsEnd' : tsEnd,
      		'tsId' : modelId,
  		},
  		'method' : 'POST'
  	});    
      	
  	request.success(function(data) {
        $('#weekplanner').fullCalendar('renderEvent', data, false); // stick? = true
  	});
	    
    request.error(function() {
         $('#notification-bar').text('An error occurred');
    });
    
}

EOF;

<?= yii2fullcalendar\yii2fullcalendar::widget([
          'options' => [
            'id' => 'weekplanner',
            'lang' => substr(\Yii::$app->language,0,2),
            'class' => 'fullcalendar'
          ],
          'header' => [
            'left' => 'prev',
            'center' => 'title',
            'right' => 'next'
          ],  
          'clientOptions' => [
          		'views' => [
          			'agendaWeek' =>[
          				'titleFormat' => 'w',
          			],
          		],
                'defaultView' => 'agendaWeek',
                'defaultDate' => '01.01.2007',
                'allDaySlot' => false,
                'minTime' => '06:00:00',
                'maxTime' => '21:00:00',
                'height' => 550,
                'selectable' => true,
                'selectHelper' => true,
                'select' => new JsExpression($JSEventSelect),
                'editable' => true,
                'eventLimit' => true,
                'eventRender' => new JsExpression($JSEventRender),
			  	'eventResize' => new JsExpression($JSEventResize),
          ],
          'ajaxEvents' => Url::toRoute(['/timeschedule/timeschedule-detail/json','id' => $model->id])
        ]);
    ?>
`

**Comment by Velheorus** [comment]
Thanks a lot!

**Comment by philippfrenzel** [comment]
done

**Comment by miguelamartinez75** [comment]
Hi Philipp!
Is there a posibility to use de hiddendays option?
Thank you!
