### ISSUE TITLE
Constraint field in Event object

### ISSUE THREAD

**Issue by mmedojevicbg** [philippfrenzel/yii2fullcalendar#56]
Hi,
According to official documentation event object contains "constraint" property
http://fullcalendar.io/docs/event_data/Event_Object/
However, yii2fullcalendar\models\Event class missing "constraint". 
I used stdClass as a workaround.

**Comment by philippfrenzel** [comment]
Hi, the Event Class is a basic template, my thought was to have an base class that can be extended by the needs of each single user/project...

so pls. do something like

```
MyCustomeEvent extends \yii2fullcalendar\models\Event...
```

Best Philipp
