### ISSUE TITLE
Add resource "resourceId" in the model

### ISSUE THREAD

**Issue by eothein** [philippfrenzel/yii2fullcalendar#57]
Dear Philipp

Thanks for the great work you have done. It could maybe be a good idea to add "resourceId" as an attribute to the event model: that way it can also be used for the scheduler functionality of the fullcalendar plugin.

Kind regards

Jens Buysse

**Comment by philippfrenzel** [comment]
@eothein you are always welcome, if you need more, pls. let me know!
