### ISSUE TITLE
Custom Views

### ISSUE THREAD

**Issue by thierryz** [philippfrenzel/yii2fullcalendar#59]
Is there a way to create a custom agendaWeek view? I would need the week to be from Monday to Sunday instead of Sunday to Saturday.
I can see that it is possible in the fullcalendar docs:
http://fullcalendar.io/docs/views/Custom_Views/

Thanks
Thierry

**Comment by thierryz** [comment]
To make the week start on Monday instead of Sunday:
        'clientOptions' => [
            'firstDay' => 1,

The default is set to 0 (Sunday), all I needed to do was to set it to 1 (Monday).

Thierry

**Comment by philippfrenzel** [comment]
thanks ;) !
