### ISSUE TITLE
composer does not install fullcalendar

### ISSUE THREAD

**Issue by xerxes87** [philippfrenzel/yii2fullcalendar#6]
I followed your installation guide, but I have the following error: 
The file or directory to be published does not exist: C:\xampp\htdocs\...\vendor\bower/fullcalendar/dist

According to your issue here: https://github.com/francoispluchino/composer-asset-plugin/issues/91
I deleted the complete vendor folder an did a composer install with the same result.

**Comment by philippfrenzel** [comment]
did you install fxp/composer-assets-plugin globally? I have this issue a several times and it always had to do with this dependency

**Comment by philippfrenzel** [comment]
updated readme for installation, pls. ensure fxp is installed

**Comment by xerxes87** [comment]
That fixed it, thank you!

**Comment by ljames604** [comment]
I followed the instructions and everything was working but for some reason, out of the blue, I am now getting an error... 

Class 'yii2fullcalendar\yii2fullcalendar' not found

can anyone help me with this? why would that be? I ran composer update several times and made sure that 	"philippfrenzel/yii2fullcalendar":"*",    and  "fxp/composer-asset-plugin": "*" are in my composer.json file.

**Comment by philippfrenzel** [comment]
Did you check your vendor folder and your class map? And maybe you need to add a \ before the classpath?

**Comment by ljames604** [comment]
Thanks for the reply Philip. I deleted my vendor directory and ran "composer update" again and that did the trick. Problem solved.

**Comment by philippfrenzel** [comment]
Great and you are always welcome!
