### ISSUE TITLE
How to add new language

### ISSUE THREAD

**Issue by vishub** [philippfrenzel/yii2fullcalendar#64]
How i can add new language translation in calender

**Comment by philippfrenzel** [comment]
pls. check original js plugin for language inclusion - after you've created the language file, you need load it via a separate asset class - this should work

**Comment by vishu-46** [comment]
i contribute a new translation for yii2fullcalender. How i can add new translation in yii2fullcalander pakage.

**Comment by philippfrenzel** [comment]
I guess you can add a js/lang folder and then put your language file in their

**Comment by philippfrenzel** [comment]
did it work?
