### ISSUE TITLE
print calendar

### ISSUE THREAD

**Issue by bokodi-dev** [philippfrenzel/yii2fullcalendar#65]
it would be nice to have the ability to disable the printAsset. I mean, print the calendar as it is.

**Comment by philippfrenzel** [comment]
Hi, if you set the PrintAsset Within view to null, this should do the job?

**Comment by bokodi-dev** [comment]
this piece of gem did the trick:
```
foreach ($this->assetBundles as $key => &$bundle) {
    if ($bundle instanceof yii2fullcalendar\PrintAsset) {
        unset($this->assetBundles[$key]);

        break;
    }
}
```

is there a better way to do it?

**Comment by philippfrenzel** [comment]
that's one way ;) can't you just address ist like $this (view) ->registerAssets(['\yii2...\PrintAsset' = NULL]); I will check my code...

**Comment by bokodi-dev** [comment]
there is no registerAssets method in View

**Comment by philippfrenzel** [comment]
oh yes you are right! got this code from yii2 really eary stage before the introduced asset class... :)

**Comment by philippfrenzel** [comment]
thanks, close this issue with the note - your example does the job
