### ISSUE TITLE
How to merge google calendar and custom events

### ISSUE THREAD

**Issue by manosl24** [philippfrenzel/yii2fullcalendar#69]
Hi,

I added google calendar with json event using this extension.
Now  how to use event click  and client side scripting events

**Comment by philippfrenzel** [comment]
pls. refer to the fullcalendar.io site on how to use events - you can pass them in the clientOptions

**Comment by manosl24** [comment]
Dear Philippfrenzel,

Thanks for your reply, in clientOptions how to pass javascript events, can you please tell me...

**Comment by philippfrenzel** [comment]
full example

`
<?= yii2fullcalendar\yii2fullcalendar::widget([
          'options' => [
            'id' => 'weekplanner',
            'lang' => substr(\Yii::$app->language,0,2),
            'class' => 'fullcalendar'
          ],
          'header' => [
            'left' => 'prev',
            'center' => 'title',
            'right' => 'next'
          ],  
          'clientOptions' => [
          		'views' => [
          			'agendaWeek' =>[
          				'titleFormat' => 'w',
          			],
          		],
                'defaultView' => 'agendaWeek',
                'defaultDate' => $defaultDate,
                'allDaySlot' => false,
                'slotDuration' => '00:15:00',
                'minTime' => '06:00:00',
                'maxTime' => '21:00:00',
                'height' => 850,
                'selectable' => true,
                'selectHelper' => true,
                'select' => new JsExpression($JSEventSelect),
                'editable' => true,
                'eventLimit' => true,
                'eventRender' => new JsExpression($JSEventRender),
			  	'eventResize' => new JsExpression($JSEventResize),
                'eventDrop' => new JsExpression($JSEventDrop),
          ],
          'ajaxEvents' => Url::toRoute(['/timeschedule/timeschedule-detail/json','id' => $model->id])
        ]);
    ?>
`

**Comment by manosl24** [comment]
Dear philippfrenzel,

Thanks for your response,i hope its helpful to me...also i added google calendar

**Comment by gasserol** [comment]
Hi, can you please point me to direction: I would like to enter data from two tables with different colors as events.. using eventSource or similar.. but I can't get it working.

**Comment by philippfrenzel** [comment]
Hey, you can prefetch events within your model (from google) and join them together with you local ones - or afterLoad you can add your local events

**Comment by philippfrenzel** [comment]
no news on this, will be closed

**Comment by gasserol** [comment]
Hallo, Danke für Deine Nachricht. Unsere Firma ist zur Zeit geschlossen, die Emails werden nur sporadisch gelesen und nicht bearbeitet. Wir wünschen Dir ein erfolgreiches neues Jahr und freuen uns, ab dem 09 Januar 2017 wieder zu Deinen Diensten zu sein. Herzlichen Dank fürs Verstädnis und freundliche Grüsse.

Buongiorno, grazie per il tuo messaggio. La nostra ditta è chiusa e i messaggi email non sono letti in modo regolare ne trattati. Ti auguriamo un excellente anno 2017 e siamo lieti di essere al tuo servizio a partire del 09 gennaio 2017.

Cordiali saluti, 
intervisio sagl - Mendrisio
