### ISSUE TITLE
Event menager

### ISSUE THREAD

**Issue by Migo2468** [philippfrenzel/yii2fullcalendar#7]
Hi @philippfrenzel I have 1 more question.

Do you use eny component to event menager to sher event on callender? 
I would write any controller but, i look you use Timetable, is any component to yii?

**Comment by philippfrenzel** [comment]
Hi, I think another user has written some kind of event manager... I'll try to reach him and ask for the component... think you'll get the final information tomorrow...

**Comment by Migo2468** [comment]
Ok thanks

**Comment by philippfrenzel** [comment]
sorry for coming back late, but I will not get one of the event management modules to be "published" would be great if you build one, to share it?

Thanks Philipp
