### ISSUE TITLE
businessHours not working

### ISSUE THREAD

**Issue by vikramsra** [philippfrenzel/yii2fullcalendar#70]
First of all thanks for the wonderful extension. I have implemented it without any problem but not able to make the businessHours option to work. here is the code I wrote

'businessHours'=>['start'=> '10:00', 'end'=> '18:00'],

**Comment by philippfrenzel** [comment]
you have to put the parameter in to the clientOptions ;) and thanks!

**Comment by vikramsra** [comment]
Did it working thanks for the quick reply
