### ISSUE TITLE
Integrate two events streams in fullcalendar

### ISSUE THREAD

**Issue by gasserol** [philippfrenzel/yii2fullcalendar#71]
Hi, can you please point me to direction: I would like to enter data from two tables with different colors as events.. using eventSource or similar.. but I can't get it working.

**Comment by gasserol** [comment]
Ok thanks guys.. i got the solution.. here is my function in controller (the mesage field contains three statuses: published, draft, scheduled):

`public function actionMessageplan() {

        $messages = Message::find()
            ->all();

        $tasks = [];

        foreach ($messages as $message) {
            $event = new \yii2fullcalendar\models\Event();

            switch ($message->status) {
                case 'published':
                    $event->id = $message->id;
                    $event->title = $message->title;
                    $event->start = gmdate("Y-m-d\TH:i:s\Z", $message->published_at);
                    $event->textColor =  'white';
                    $event->backgroundColor = 'green';
                    break;
                case 'draft':
                    $event->id = $message->id;
                    $event->title = $message->title;
                    $event->start = gmdate("Y-m-d\TH:i:s\Z", $message->created_at);
                    $event->textColor =  'black';
                    $event->backgroundColor = 'white';
                    $event->borderColor = 'black';
                    break;
                case 'scheduled':
                    $event->id = $message->id;
                    $event->title = $message->title;
                    $event->start = gmdate("Y-m-d\TH:i:s\Z", $message->created_at);
                    $event->textColor =  'white';
                    $event->backgroundColor = 'orange';
                    break;
            }

            $tasks[] = $event;
        }

        return $this->render('messageplan', [
            'events' => $tasks,
            //'drafts' => $tasks1,
        ]);`

and the view file contains the following widget call:

`<?= \yii2fullcalendar\yii2fullcalendar::widget([
        'events'=> $events,
    ]);
    ?>`

So in fact I use just one 'stream' but pass some colors over to each element. You can close this issue. Thanks anyway.

**Comment by philippfrenzel** [comment]
Hey, sorry I did't get your request in time! And thank you for this nice summary - others will love it as a how to!
