### ISSUE TITLE
Class /yii2fullcalendar/model/Event not found

### ISSUE THREAD

**Issue by djnordeen** [philippfrenzel/yii2fullcalendar#75]
Hello,
I had the calendar working on my laptop server. However when uploaded to web host. I get the following error  'Class 'philippfrenzel\yii2fullcalendar\yii2fullcalendar\models\Event' not found' .
Here is the statement that it fails on:  $event = new \yii2fullcalendar\models\Event();

Any help would be most appreciated.
Thanks

**Comment by philippfrenzel** [comment]
You miss the correct namespace for the event;) try to add Philippfrenzel\ and see if it works

**Comment by djnordeen** [comment]
Hello,  I found out the problem.  It was because of the yiisoft/extensions.php file  was missing the Yii2fullcalendar namespace.  It happened when I uploaded to the web.  I searched the internet for "yii2 class plugin not found"  the answer came up.

Thanks for the response and great plugin.

**Comment by philippfrenzel** [comment]
thanks for sharing the solution!
