### ISSUE TITLE
Error when installing via Composer

### ISSUE THREAD

**Issue by p2made** [philippfrenzel/yii2fullcalendar#76]
In the last 36 hours Composer has started throwing an error when updating projects that have fullcalendar as a dependancy (or, like mine, as a dependancy of a dependancy, namely yii2fullcalendar)...

```
[UnexpectedValueException]                                            
  Could not parse version constraint >=~2: Invalid version string "~2"
```

That is, somewhere in the dependancy chain of fullcalendar, something declares the impossible version constraint `>=~2`.

I have also reported this issue on [fullcalendar](https://github.com/fullcalendar/fullcalendar/issues/3531).

**Comment by philippfrenzel** [comment]
Hi, which fxp/composer-plugin are you using?

**Comment by p2made** [comment]
Version 1.2.2.

**Comment by nasyrov** [comment]
same here

**Comment by yafater** [comment]
It's same for me

**Comment by philippfrenzel** [comment]
I get the same mistake here  - it happened due to my fxp update :/ I will check if the changed something within the version "solver" as it's related to the bower dependencies...

**Comment by p2made** [comment]
The developer of `fxp/composer-plugin` has advised of a fix in progress. For the moment this gets us going again...

```
$ composer global require fxp/composer-asset-plugin:~1.3@dev
```
