### ISSUE TITLE
Composer requisre fail ~2

### ISSUE THREAD

**Issue by lukBarros** [philippfrenzel/yii2fullcalendar#77]
composer require philippfrenzel/yii2fullcalendar "3.0.3"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
                                                             
Installation failed, reverting ./composer.json to its original content.

                                                                        
  [UnexpectedValueException]                                            
  Could not parse version constraint >=~2: Invalid version string "~2"

**Comment by philippfrenzel** [comment]
Hi, pls. just check #76 which handles your question - the issue related to fxp/composer-asset-plugin if you install the latest dev version it will work again!
