### ISSUE TITLE
eventClick not working

### ISSUE THREAD

**Issue by jorgejavier** [philippfrenzel/yii2fullcalendar#8]
Hi I'm using yii2fullcalendar extension. It works fine, at least it renders the calendar and the events I set  from my controller, but I can make the eventClick or drag to work. Not sure what's wrong.

**Comment by philippfrenzel** [comment]
Hi, 

if you explain more what you are trying to do or what isn't working?

You'll have to enable drag n drop:

```
yii2fullcalendar\yii2fullcalendar::widget(array(
              'clientOptions' => [
                    'selectable' => true,
                    'selectHelper' => true,
                    'droppable' => true,
                    'editable' => true,
                    'drop' => new JsExpression($JSDropEvent),
                    'select' => new JsExpression($JSCode),
                    'eventClick' => new JsExpression($JSEventClick),
                    'defaultDate' => date('Y-m-d')
              ],
              'ajaxEvents' => Url::toRoute(['/site/jsoncalendar'])
            ));
```

and this as drop handler:

```
$JSDropEvent = <<<EOF
function(date) {
    alert("Dropped on " + date.format());
    if ($('#drop-remove').is(':checked')) {
        // if so, remove the element from the "Draggable Events" list
        $(this).remove();
    }
}
EOF;
```

**Comment by HanktheTankCDN** [comment]
Hi Philipp
I cannot get the eventClick to work either.

yii2fullcalendar\yii2fullcalendar::widget([
    'options' => [
        'language' => 'en',
      ],
    'clientOptions' => [
        'eventClick' => 'js:function(date, jsEvent, view) {
            alert("a day has been clicked!");
        }',
    ],
    'events' => $events,
]);

Can you provide the widget declaration from your sample on Beeye?

**Comment by HanktheTankCDN** [comment]
Never mind figured it out, forgot the JSExpression('function...')

**Comment by philippfrenzel** [comment]
Ok, i'm happy you figured it Out! I will Update docs to help New Users to not get Stuck with the Same issue! Thanks

**Comment by jorgejavier** [comment]
Hi, thanks for your quick answer, I wasnt sure of how to set the js functions for drag and drop when creating the widget in php, this example really helped me a lot!! Thanks for your help.

**Comment by davidscr** [comment]
Hey Philipp,
my drag/drop events are also not fired. I'm initializing the widget like this:

  <?= \yii2fullcalendar\yii2fullcalendar::widget(
      [      
		'options' => [  
			'lang' => 'en',
		],
		'clientOptions' => [ 
			'eventDragStop' => new JsExpression('js:function( event, jsEvent, ui, view ) {    alert("test"); }'),
		],
		'events'=> $eventarray,
      ]
	);
    ?>

**Comment by philippfrenzel** [comment]
shouldn't it be just 'drop' in the client options?
