### ISSUE TITLE
install errors : composer require philippfrenzel/yii2fullcalendar "*"

### ISSUE THREAD

**Issue by awebc** [philippfrenzel/yii2fullcalendar#80]
composer require philippfrenzel/yii2fullcalendar "*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
                                                                         
Installation failed, reverting ./composer.json to its original content.

                                                                        
  [UnexpectedValueException]                                            
  Could not parse version constraint >=~2: Invalid version string "~2"

**Comment by philippfrenzel** [comment]
pls. update your composer fxp plugin ... check out documentation pls.
