### ISSUE TITLE
Change the language settings

### ISSUE THREAD

**Issue by christianchf** [philippfrenzel/yii2fullcalendar#81]
Hello,

how could you change the language settings to Spanish?

Thanks.

**Comment by philippfrenzel** [comment]
within the plugin options you can set the language to es -> pls. see documentation here:
https://fullcalendar.io/js/fullcalendar-3.4.0/demos/locales.html
Eventually within the extension options you need to set the language too - to get the es.js assets loaded...;)

**Comment by christianchf** [comment]
Thank you very much for the help @philippfrenzel :+1:  :)
