### ISSUE TITLE
eventResize is not mapped/handled

### ISSUE THREAD

**Issue by paciliojoe** [philippfrenzel/yii2fullcalendar#83]
It looks like many of the FullCalendar event (handlers) are mapped, (ie eventDrop) but eventResize is not.  Simply adding an eventResize property to the yii2fullcalendar class and mapping the property in the getClientOptions() function fixes the issue.

**Comment by philippfrenzel** [comment]
can you pls. add a pull request? Thanks!

**Comment by philippfrenzel** [comment]
just saw your pull request, thanks for adding
