### ISSUE TITLE
event render callback

### ISSUE THREAD

**Issue by qdii** [philippfrenzel/yii2fullcalendar#9]
I am not sure if this is feasible in the current version. Would it be possible to let an user of the class specify its own eventRender callback function?

**Comment by philippfrenzel** [comment]
hmm, sounds interesting and should be possible;) what exactly are you trying to do?

**Comment by philippfrenzel** [comment]
Have you seen this:

http://fullcalendar.io/docs/event_rendering/eventRender/

And you can pass this over like:

```
$js = EOF<<<
function(event, element) {
        element.qtip({
            content: event.description
        });
    }
EOF;

options...
'eventRender' => new JsExpression($js);
```

**Comment by philippfrenzel** [comment]
@qdii - is this working now?

**Comment by qdii** [comment]
Hey Philippe,
Thanks, yes, this works perfectly!
