### ISSUE TITLE
Quick start example error

### ISSUE THREAD

**Issue by shilecro** [philippfrenzel/yii2fullcalendar#90]
`  $event->nonstandard = [
    'field1' => 'Something I want to be included in object #1',
    'field2' => 'Something I want to be included in object #2',
  ],`
To:
`  $Event->nonstandard = [
    'field1' => 'Something I want to be included in object #1',
    'field2' => 'Something I want to be included in object #2',
  ];`

**Comment by philippfrenzel** [comment]
Hey @shilecro thanks for the hint - I cleaned it! ;) Always welcome to improve!

**Comment by shilecro** [comment]
Glad to help, but still you have to change $event to $Event :)
