### ISSUE TITLE
Missing "dist" folder in bower fullcalendar package

### ISSUE THREAD

**Issue by sosojni** [philippfrenzel/yii2fullcalendar#91]
I tried to update my project and things went south with file permissions so i deleted vendor folder and run "composer update" command. Everything goes smooth but now im missing "dist" folder from bower/fullcalendar
This is not first time i recreated vendor folder but this is first time something like this happened.

**Comment by philippfrenzel** [comment]
Hey, I have the same issue and I don't find a solution for this currently - will make some more tests today - help welcome

**Comment by sosojni** [comment]
I think something changes in fullcalendar project. Master has no dist folder but if you go to "tag" there is dist folder. For example: https://github.com/fullcalendar/fullcalendar/tree/v3.5.1

**Comment by sosojni** [comment]
something like: "vendor/package": "dev-master#v0.5.0" (with correct fullcalendar version ofc)

**Comment by philippfrenzel** [comment]
Hey, just updated the composer and the core assets - let's see if it works

**Comment by sosojni** [comment]
I get this error now: The file or directory to be published does not exist: C:\xampp70\htdocs\pristup\backend\vendor/bower-asset/fullcalendar/tag/dist
There is dist folder in bower-assets now, but component is searching for it in wrong place.

**Comment by sosojni** [comment]
After source dir fix ( https://github.com/philippfrenzel/yii2fullcalendar/pull/92 ) , it is working fine if i include it in my composer.json as: "philippfrenzel/yii2fullcalendar": "dev-master"

**Comment by sosojni** [comment]
I have tested your new release. Im afraid, it is not working. On my brand i created  (where im testing it) it's working only if i use specific version like: "bower-asset/fullcalendar": "3.5.0"
https://github.com/sosojni/yii2fullcalendar/blob/master/composer.json

**Comment by philippfrenzel** [comment]
Well, still not working - I'm kind of lost while the dist folder didn't get generated :/

**Comment by sosojni** [comment]
Thanks, it's working now!

**Comment by philippfrenzel** [comment]
moved to 3.6.2 and fullcalender distribution works back normal - close this for now

**Comment by Papudi** [comment]
Im not sure if this is the right fix, but all you need to do is dump the dist folder from the fullcalender git repo into the bower/fullcalendar folder.

**Comment by ahmadsheikhabdrahim** [comment]
I'm also facing the same issue. Yesterday after I'm ran composer update, I'm faced with missing 'dist' folder. I'm tried to delete the whole vendor folder but still not working for me. After I'm tried solution from Papudi, it's working. My last version was 3.7.1.0. After ran composer update my philippfrenzel/yii2fullcalendar version changed to 4.0.2.0.
