### ISSUE TITLE
How remove scroller

### ISSUE THREAD

**Issue by Maksclub** [philippfrenzel/yii2fullcalendar#94]
Hello, help me plz !

How to remove scroller?
https://drive.google.com/open?id=0B3Xaem3-nptWUjdfd25vUDZTOGM

I'm want get result:
https://drive.google.com/open?id=0B3Xaem3-nptWeWc2dk5EbDJDMkE

Thanks

**Comment by philippfrenzel** [comment]
Hey,

you need to append css in your app assets and load them after the extension assets - pls. check out fullcalendar.io for hints on how to modify the module

**Comment by Maksclub** [comment]
Thanks, i'm define you wiget
```php

namespace backend\widgets;


class yii2fullcalendar extends \yii2fullcalendar\yii2fullcalendar
{
    // Property 'contentHeight' absent in yii2fullcalendar
    // because add public property, add default value and define registerPlugin
    public $contentHeight = 'auto';

    protected function registerPlugin()
    {
        if(isset($this->contentHeight) && !isset($this->clientOptions['contentHeight']))
        {
            $this->clientOptions['contentHeight'] = $this->contentHeight;
        }
        parent::registerPlugin();
    }
}
```

**Comment by philippfrenzel** [comment]
@Maksclub thanks - maybe you can write a pull request so this can be placed in the lib for all users ? ;)

**Comment by Maksclub** [comment]
ok :) I'll do

**Comment by philippfrenzel** [comment]
added the attribute with commit f86535d

**Comment by alladas** [comment]
Hi,
Very late, but this could help others. Please try:
`'clientOptions' => [
...
'aspectRatio' => 1
]
,`

**Comment by philippfrenzel** [comment]
@alladas thanks for sharing solution
