### ISSUE TITLE
external events

### ISSUE THREAD

**Issue by marcosilvestroni** [philippfrenzel/yii2fullcalendar#95]
Hi, 

I didn't found any documentation about the drop funcion for the externals events , the option drop doesn't work is setted. 

Here my code:

```
<?= yii2fullcalendar\yii2fullcalendar::widget([
    'options' => [
      'lang' => 'it',
      'droppable' => true,
      'drop' => 'function(date) {
        alert("Dropped on " + date.format());
      }',
    ],
    'ajaxEvents' => Url::to(['/planning/jsoncalendar']),
    'eventDrop' => ' function(event, delta, revertFunc) {   
      $.ajax({
        method: "POST",
        url: "/planning/updatefast?id=" + event.id,
        data: { start: event.start.format(), end : event.end.format() }
      })
        .error(function(){
          revertFunc();
        });                 
    }',
    'eventResize' => ' function(event, delta, revertFunc) {   
      $.ajax({
        method: "POST",
        url: "/planning/updatefast?id=" + event.id,
        data: { start: event.start.format(), end : event.end.format() }
      })
        .error(function(){
          revertFunc();
        });                 
    }',
    
    
   
  ]);
?>
```

**Comment by philippfrenzel** [comment]
Hi, you should pls. take a look at the original fullcalendar.io it has samples on how to implement this functionality

**Comment by philippfrenzel** [comment]
@marcosilvestroni any news on this? Still not working?

**Comment by philippfrenzel** [comment]
@marcosilvestroni I just reviewed your issue and I think you'll have to add the drop event into the clientOptions? Pls. let me know if this works out

**Comment by marcosilvestroni** [comment]
Hi @philippfrenzel, I finaly used the fullcalendar via jquery , I 'va to to use in anther project and I will try to implement via yii2 widget the way you suggest me! thks

**Comment by philippfrenzel** [comment]
Hi, that's fine ;) Acutally this widget allows you to use everything with the jquery api;) so I'll close this issue for now - pls. reopen if you need further assistance ;)
