### ISSUE TITLE
PHP Parse Error – yii\base\ErrorException  syntax error, unexpected '=>' (T_DOUBLE_ARROW)

### ISSUE THREAD

**Issue by nayoma** [philippfrenzel/yii2fullcalendar#96]
![fireshot capture 12 - yii_base_errorexception - http___dev sample frontend kredible com_](https://user-images.githubusercontent.com/29333716/31988677-8aad3a58-b98d-11e7-8342-da384e3218e6.png)

**Comment by masihfathi** [comment]
in this commit the problem solved by the developer.
https://github.com/philippfrenzel/yii2fullcalendar/commit/e5b4b6c67851afb09025bbb363727afe27075d2a
i think if you change package to dev-master problem solved.

**Comment by nayoma** [comment]
Problem solved.
Thanks.

**Comment by philippfrenzel** [comment]
yes dev-master solve this issue - sorry currently trying to enhance the plugin so some commits break the lib for a couple of hours ... stick to old versions if you wanna be "save"
