### ISSUE TITLE
Event constraint

### ISSUE THREAD

**Issue by tomashavlas** [philippfrenzel/yii2fullcalendar#98]
Hello,

I can't set constraint (https://fullcalendar.io/docs/event_ui/eventConstraint/ - it is also listed here https://fullcalendar.io/docs/event_data/Event_Object/) to fullcalendar event through Event object in yii. It crashes with following error:

```
<pre>Exception (Unknown Property) &#039;yii\base\UnknownPropertyException&#039; with message &#039;Setting unknown property: Event::constraint&#039; 

in /var/www/html/vendor/yiisoft/yii2/base/Component.php:203
```

I'm trying to assign it like that

```
$event = new Event();
...
$event->constraint = 'businessHours';
```

Would it be possible to add support for this argument?

**Comment by philippfrenzel** [comment]
Hey, first you should write your own event class extending the default one - and then pls. check the custom field documentation - this should help you to add individual fields! 

Within your event class you can then use the hasOne or hasMany logic from activerecord ;)

**Comment by tomashavlas** [comment]
I think you haven't understood me :) I'm not asking for support for custom / nonstandard field - the 'constraint' field is a standard field of Event Object of FullCalendar it is documented here https://fullcalendar.io/docs/event_data/Event_Object/.

What I need to do is pass constraint from my yii2 backend to fullcalendar Event Object like I can pass any other standard field (title, start, end, color, etc ...). Or is there a reason why this field is not implemented here?

**Comment by philippfrenzel** [comment]
Hi,

do you have some sample code so I can understand that issue better?

**Comment by tomashavlas** [comment]
Well first I believe that `yii2fullcalendar\models\Event` is supposed to mirror FullCalendar Event Object => if this assumption is wrong, then just close this issue as invalid please. But if it is supposed to have the same properties then here is example what I need to do
```
<?php

public function actionIssueList()
{
    $tasks = Taks::findAll();
    $events = [];

    foreach ($taks as $task) {
        $event = new Event();
        $event->id = $task->id;
        $event->title = $task->title;
        $event->description = $task->description
        $event->start = date('Y-m-d\TH:i:s\Z', $task->begin);
        $event->end = date('Y-m-d\TH:i:s\Z', $task->finish);
        $event->color = $task->getColorCode();
        // following statement throws afformentioned error
        $event->constraint = 'businessHours';
        
        $events[] = $event; 
    }

    Yii::$app->response->format = Response::FORMAT_JSON;

    return $events;
}
```

this is placed in some controller and fullcalendar uses this method as ajax event source.

**Comment by tomashavlas** [comment]
I've created a pull request that should resolve this issue.
