### ISSUE TITLE
Week view events no longer rendering following update

### ISSUE THREAD

**Issue by spiro-stathakis** [philippfrenzel/yii2fullcalendar#99]
Hi there, 

Following an update via composer, I have a problem where there are no longer events being rendered through week view. If I switch to month view, the events do get rendered and then switching back to week view will show the events.  Have any recent changes affected how the calendar is working ?

**Comment by philippfrenzel** [comment]
Pls. check now - fullcalendar just updated to 3.7 so this will fix this issue - sorry for the inconvinience
